# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1934, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditlog = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditlog.setGeometry(QtCore.QRect(10, 730, 511, 91))
        self.textEditlog.setObjectName("textEditlog")
        self.pB_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Start.setGeometry(QtCore.QRect(450, 50, 75, 23))
        self.pB_Start.setAutoFillBackground(False)
        self.pB_Start.setObjectName("pB_Start")
        self.pB_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Stop.setGeometry(QtCore.QRect(530, 50, 75, 23))
        self.pB_Stop.setAutoFillBackground(False)
        self.pB_Stop.setObjectName("pB_Stop")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 431, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pB_SaveSetup = QtWidgets.QPushButton(self.tab)
        self.pB_SaveSetup.setGeometry(QtCore.QRect(340, 110, 75, 23))
        self.pB_SaveSetup.setAutoFillBackground(False)
        self.pB_SaveSetup.setObjectName("pB_SaveSetup")
        self.pB_connect = QtWidgets.QPushButton(self.tab)
        self.pB_connect.setGeometry(QtCore.QRect(182, 20, 75, 23))
        self.pB_connect.setAutoFillBackground(False)
        self.pB_connect.setObjectName("pB_connect")
        self.status_device = QtWidgets.QLabel(self.tab)
        self.status_device.setGeometry(QtCore.QRect(10, 57, 401, 16))
        self.status_device.setStatusTip("")
        self.status_device.setAutoFillBackground(True)
        self.status_device.setObjectName("status_device")
        self.pB_LoadSetup = QtWidgets.QPushButton(self.tab)
        self.pB_LoadSetup.setGeometry(QtCore.QRect(260, 110, 75, 23))
        self.pB_LoadSetup.setAutoFillBackground(False)
        self.pB_LoadSetup.setObjectName("pB_LoadSetup")
        self.cB_comport = QtWidgets.QComboBox(self.tab)
        self.cB_comport.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.cB_comport.setToolTip("")
        self.cB_comport.setObjectName("cB_comport")
        self.pB_refresh = QtWidgets.QPushButton(self.tab)
        self.pB_refresh.setEnabled(True)
        self.pB_refresh.setGeometry(QtCore.QRect(102, 20, 75, 23))
        self.pB_refresh.setAutoFillBackground(False)
        self.pB_refresh.setObjectName("pB_refresh")
        self.pB_Set_Setup = QtWidgets.QPushButton(self.tab)
        self.pB_Set_Setup.setEnabled(True)
        self.pB_Set_Setup.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pB_Set_Setup.setAutoFillBackground(False)
        self.pB_Set_Setup.setObjectName("pB_Set_Setup")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 211, 204))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.LayoutParameters = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.LayoutParameters.setContentsMargins(0, 0, 0, 0)
        self.LayoutParameters.setHorizontalSpacing(6)
        self.LayoutParameters.setObjectName("LayoutParameters")
        self.Current_Amplitude = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.Current_Amplitude.setDecimals(4)
        self.Current_Amplitude.setMinimum(0.0001)
        self.Current_Amplitude.setMaximum(10.0)
        self.Current_Amplitude.setSingleStep(0.1)
        self.Current_Amplitude.setObjectName("Current_Amplitude")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Current_Amplitude)
        self.label_Burst = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst.setObjectName("label_Burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Burst)
        self.Burst = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.Burst.setMaximum(255)
        self.Burst.setObjectName("Burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Burst)
        self.label_minF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_minF.setObjectName("label_minF")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_minF)
        self.label_maxF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxF.setObjectName("label_maxF")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_maxF)
        self.label_Steps = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Steps.setObjectName("label_Steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Steps)
        self.Steps = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.Steps.setMaximum(255)
        self.Steps.setObjectName("Steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Steps)
        self.label_Burst_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst_5.setObjectName("label_Burst_5")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_Burst_5)
        self.cB_Scale = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cB_Scale.setEditable(False)
        self.cB_Scale.setMaxVisibleItems(2)
        self.cB_Scale.setObjectName("cB_Scale")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cB_Scale)
        self.label_FrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_FrameRate.setObjectName("label_FrameRate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_FrameRate)
        self.FrameRate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.FrameRate.setDecimals(3)
        self.FrameRate.setMaximum(100.0)
        self.FrameRate.setSingleStep(0.001)
        self.FrameRate.setObjectName("FrameRate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.FrameRate)
        self.label_Current_Amplitude = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Current_Amplitude.setObjectName("label_Current_Amplitude")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Current_Amplitude)
        self.maxF = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.maxF.setAutoFillBackground(False)
        self.maxF.setMinimum(100.0)
        self.maxF.setMaximum(1000000.0)
        self.maxF.setObjectName("maxF")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxF)
        self.minF = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.minF.setMinimum(100.0)
        self.minF.setMaximum(1000000.0)
        self.minF.setObjectName("minF")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minF)
        self.MaxFrameRate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.MaxFrameRate.setDecimals(3)
        self.MaxFrameRate.setMaximum(100.0)
        self.MaxFrameRate.setSingleStep(0.001)
        self.MaxFrameRate.setObjectName("MaxFrameRate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.MaxFrameRate)
        self.label_maxFrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxFrameRate.setObjectName("label_maxFrameRate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_maxFrameRate)
        self.pB_disconnect = QtWidgets.QPushButton(self.tab)
        self.pB_disconnect.setGeometry(QtCore.QRect(262, 20, 75, 23))
        self.pB_disconnect.setToolTip("")
        self.pB_disconnect.setAutoFillBackground(False)
        self.pB_disconnect.setObjectName("pB_disconnect")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 150, 121, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayoutExcitationPattern = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayoutExcitationPattern.setContentsMargins(0, 0, 0, 0)
        self.vLayoutExcitationPattern.setObjectName("vLayoutExcitationPattern")
        self.label_ExcitationPattern = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ExcitationPattern.setObjectName("label_ExcitationPattern")
        self.vLayoutExcitationPattern.addWidget(self.label_ExcitationPattern)
        self.Excitation_pattern = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.Excitation_pattern.setObjectName("Excitation_pattern")
        self.Excitation_pattern.setColumnCount(2)
        self.Excitation_pattern.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Excitation_pattern.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Excitation_pattern.setHorizontalHeaderItem(1, item)
        self.Excitation_pattern.horizontalHeader().setDefaultSectionSize(40)
        self.vLayoutExcitationPattern.addWidget(self.Excitation_pattern)
        self.pB_Get_Setup = QtWidgets.QPushButton(self.tab)
        self.pB_Get_Setup.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.pB_Get_Setup.setAutoFillBackground(False)
        self.pB_Get_Setup.setObjectName("pB_Get_Setup")
        self.pB_Reset = QtWidgets.QPushButton(self.tab)
        self.pB_Reset.setGeometry(QtCore.QRect(170, 110, 75, 23))
        self.pB_Reset.setAutoFillBackground(False)
        self.pB_Reset.setObjectName("pB_Reset")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 400, 201, 166))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LayoutComConfig = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.LayoutComConfig.setContentsMargins(0, 0, 0, 0)
        self.LayoutComConfig.setObjectName("LayoutComConfig")
        self.label_SN = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_SN.setObjectName("label_SN")
        self.LayoutComConfig.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_SN)
        self.SN = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.SN.setToolTip("")
        self.SN.setWhatsThis("")
        self.SN.setInputMask("")
        self.SN.setFrame(True)
        self.SN.setObjectName("SN")
        self.LayoutComConfig.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SN)
        self.label_IP = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_IP.setObjectName("label_IP")
        self.LayoutComConfig.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_IP)
        self.IP_Adress = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.IP_Adress.setToolTip("")
        self.IP_Adress.setWhatsThis("")
        self.IP_Adress.setInputMask("")
        self.IP_Adress.setFrame(True)
        self.IP_Adress.setObjectName("IP_Adress")
        self.LayoutComConfig.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IP_Adress)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.LayoutComConfig.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.MAC_Adress = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.MAC_Adress.setObjectName("MAC_Adress")
        self.LayoutComConfig.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.MAC_Adress)
        self.DHCP_Activated = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.DHCP_Activated.setChecked(False)
        self.DHCP_Activated.setObjectName("DHCP_Activated")
        self.LayoutComConfig.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DHCP_Activated)
        self.Excitation_Stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Excitation_Stamp.setChecked(False)
        self.Excitation_Stamp.setObjectName("Excitation_Stamp")
        self.LayoutComConfig.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Excitation_Stamp)
        self.Current_Stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Current_Stamp.setChecked(False)
        self.Current_Stamp.setObjectName("Current_Stamp")
        self.LayoutComConfig.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Current_Stamp)
        self.Time_Stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Time_Stamp.setChecked(False)
        self.Time_Stamp.setObjectName("Time_Stamp")
        self.LayoutComConfig.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Time_Stamp)
        self.label_OutputConfig = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_OutputConfig.setObjectName("label_OutputConfig")
        self.LayoutComConfig.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_OutputConfig)
        self.hsb = QtWidgets.QScrollBar(self.tab)
        self.hsb.setGeometry(QtCore.QRect(80, 630, 160, 16))
        self.hsb.setOrientation(QtCore.Qt.Horizontal)
        self.hsb.setObjectName("hsb")
        self.pB_loadinjpattern = QtWidgets.QPushButton(self.tab)
        self.pB_loadinjpattern.setGeometry(QtCore.QRect(290, 600, 75, 23))
        self.pB_loadinjpattern.setAutoFillBackground(False)
        self.pB_loadinjpattern.setObjectName("pB_loadinjpattern")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pB_ImagRec = QtWidgets.QPushButton(self.tab_2)
        self.pB_ImagRec.setGeometry(QtCore.QRect(340, 260, 75, 23))
        self.pB_ImagRec.setAutoFillBackground(False)
        self.pB_ImagRec.setObjectName("pB_ImagRec")
        self.pB_LoadDataSet = QtWidgets.QPushButton(self.tab_2)
        self.pB_LoadDataSet.setGeometry(QtCore.QRect(330, 10, 75, 23))
        self.pB_LoadDataSet.setAutoFillBackground(False)
        self.pB_LoadDataSet.setObjectName("pB_LoadDataSet")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 301, 211))
        self.textEdit.setObjectName("textEdit")
        self.pB_Plot = QtWidgets.QPushButton(self.tab_2)
        self.pB_Plot.setGeometry(QtCore.QRect(340, 220, 75, 23))
        self.pB_Plot.setAutoFillBackground(False)
        self.pB_Plot.setObjectName("pB_Plot")
        self.pB_Uplot = QtWidgets.QPushButton(self.tab_2)
        self.pB_Uplot.setGeometry(QtCore.QRect(340, 190, 75, 23))
        self.pB_Uplot.setAutoFillBackground(False)
        self.pB_Uplot.setObjectName("pB_Uplot")
        self.cB_Frame_indx = QtWidgets.QComboBox(self.tab_2)
        self.cB_Frame_indx.setGeometry(QtCore.QRect(340, 110, 69, 22))
        self.cB_Frame_indx.setObjectName("cB_Frame_indx")
        self.label_Frame_indx = QtWidgets.QLabel(self.tab_2)
        self.label_Frame_indx.setGeometry(QtCore.QRect(340, 70, 91, 31))
        self.label_Frame_indx.setObjectName("label_Frame_indx")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 260, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showReal = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showReal.setChecked(True)
        self.showReal.setObjectName("showReal")
        self.gridLayout_2.addWidget(self.showReal, 0, 0, 1, 1)
        self.showImag = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showImag.setObjectName("showImag")
        self.gridLayout_2.addWidget(self.showImag, 1, 0, 1, 1)
        self.showPhase = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showPhase.setObjectName("showPhase")
        self.gridLayout_2.addWidget(self.showPhase, 1, 1, 1, 1)
        self.showAbsValue = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.showAbsValue.setObjectName("showAbsValue")
        self.gridLayout_2.addWidget(self.showAbsValue, 2, 0, 1, 1)
        self.showMagnitude = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showMagnitude.setObjectName("showMagnitude")
        self.gridLayout_2.addWidget(self.showMagnitude, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 325, 345, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_vmax_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_2.setObjectName("label_vmax_2")
        self.gridLayout.addWidget(self.label_vmax_2, 0, 2, 1, 1)
        self.rB_TimeDiff = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_TimeDiff.setObjectName("rB_TimeDiff")
        self.gridLayout.addWidget(self.rB_TimeDiff, 1, 0, 1, 1)
        self.rB_FreqDiff = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_FreqDiff.setObjectName("rB_FreqDiff")
        self.gridLayout.addWidget(self.rB_FreqDiff, 2, 0, 1, 1)
        self.cB_Frequency4TD = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_Frequency4TD.setCurrentText("")
        self.cB_Frequency4TD.setObjectName("cB_Frequency4TD")
        self.gridLayout.addWidget(self.cB_Frequency4TD, 1, 1, 1, 1)
        self.pB_UpdateRef4TD = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pB_UpdateRef4TD.setAutoFillBackground(False)
        self.pB_UpdateRef4TD.setObjectName("pB_UpdateRef4TD")
        self.gridLayout.addWidget(self.pB_UpdateRef4TD, 1, 3, 1, 1)
        self.cB_Frequency4FD_0 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_Frequency4FD_0.setCurrentText("")
        self.cB_Frequency4FD_0.setObjectName("cB_Frequency4FD_0")
        self.gridLayout.addWidget(self.cB_Frequency4FD_0, 2, 1, 1, 1)
        self.cB_Frequency4FD_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_Frequency4FD_1.setObjectName("cB_Frequency4FD_1")
        self.gridLayout.addWidget(self.cB_Frequency4FD_1, 2, 3, 1, 1)
        self.rB_RawData = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_RawData.setChecked(True)
        self.rB_RawData.setObjectName("rB_RawData")
        self.gridLayout.addWidget(self.rB_RawData, 0, 0, 1, 1)
        self.cB_Frequency = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_Frequency.setObjectName("cB_Frequency")
        self.gridLayout.addWidget(self.cB_Frequency, 0, 1, 1, 1)
        self.label_vmax_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_4.setObjectName("label_vmax_4")
        self.gridLayout.addWidget(self.label_vmax_4, 2, 2, 1, 1)
        self.label_vmax_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_3.setObjectName("label_vmax_3")
        self.gridLayout.addWidget(self.label_vmax_3, 1, 2, 1, 1)
        self.label_vmax_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_5.setObjectName("label_vmax_5")
        self.gridLayout.addWidget(self.label_vmax_5, 2, 4, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 230, 220, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cB_ReconstructionAlgorithm = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cB_ReconstructionAlgorithm.setObjectName("cB_ReconstructionAlgorithm")
        self.gridLayout_3.addWidget(self.cB_ReconstructionAlgorithm, 1, 2, 1, 1)
        self.rB_plot_graph = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.rB_plot_graph.setChecked(True)
        self.rB_plot_graph.setObjectName("rB_plot_graph")
        self.gridLayout_3.addWidget(self.rB_plot_graph, 0, 0, 1, 1)
        self.rB_Image = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.rB_Image.setObjectName("rB_Image")
        self.gridLayout_3.addWidget(self.rB_Image, 1, 0, 1, 1)
        self.label_vmax_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vmax_6.setObjectName("label_vmax_6")
        self.gridLayout_3.addWidget(self.label_vmax_6, 1, 1, 1, 1)
        self.checkB_diff = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkB_diff.setObjectName("checkB_diff")
        self.gridLayout_3.addWidget(self.checkB_diff, 0, 2, 1, 1)
        self.checkB_Uplot = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkB_Uplot.setObjectName("checkB_Uplot")
        self.gridLayout_3.addWidget(self.checkB_Uplot, 0, 1, 1, 1)
        self.pB_loadRef = QtWidgets.QPushButton(self.tab_2)
        self.pB_loadRef.setGeometry(QtCore.QRect(340, 150, 75, 23))
        self.pB_loadRef.setAutoFillBackground(False)
        self.pB_loadRef.setObjectName("pB_loadRef")
        self.checkB_YLog = QtWidgets.QCheckBox(self.tab_2)
        self.checkB_YLog.setGeometry(QtCore.QRect(330, 460, 72, 17))
        self.checkB_YLog.setObjectName("checkB_YLog")
        self.eit_FEMRefinement = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.eit_FEMRefinement.setGeometry(QtCore.QRect(250, 290, 90, 20))
        self.eit_FEMRefinement.setDecimals(4)
        self.eit_FEMRefinement.setMinimum(0.0)
        self.eit_FEMRefinement.setMaximum(10.0)
        self.eit_FEMRefinement.setSingleStep(0.001)
        self.eit_FEMRefinement.setProperty("value", 0.1)
        self.eit_FEMRefinement.setObjectName("eit_FEMRefinement")
        self.label_FEMRefinement = QtWidgets.QLabel(self.tab_2)
        self.label_FEMRefinement.setGeometry(QtCore.QRect(250, 270, 91, 20))
        self.label_FEMRefinement.setObjectName("label_FEMRefinement")
        self.replay_refresh_time = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.replay_refresh_time.setGeometry(QtCore.QRect(290, 600, 90, 20))
        self.replay_refresh_time.setDecimals(1)
        self.replay_refresh_time.setMinimum(1.0)
        self.replay_refresh_time.setMaximum(10.0)
        self.replay_refresh_time.setSingleStep(1.0)
        self.replay_refresh_time.setProperty("value", 1.0)
        self.replay_refresh_time.setObjectName("replay_refresh_time")
        self.label_replay_refresh_time = QtWidgets.QLabel(self.tab_2)
        self.label_replay_refresh_time.setGeometry(QtCore.QRect(290, 580, 91, 20))
        self.label_replay_refresh_time.setObjectName("label_replay_refresh_time")
        self.Slider_replay_time = QtWidgets.QSlider(self.tab_2)
        self.Slider_replay_time.setGeometry(QtCore.QRect(10, 640, 411, 22))
        self.Slider_replay_time.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_replay_time.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_replay_time.setTickInterval(0)
        self.Slider_replay_time.setObjectName("Slider_replay_time")
        self.pB_gotoend = QtWidgets.QPushButton(self.tab_2)
        self.pB_gotoend.setGeometry(QtCore.QRect(110, 600, 25, 25))
        self.pB_gotoend.setAutoFillBackground(False)
        self.pB_gotoend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_gotoend.setIcon(icon)
        self.pB_gotoend.setAutoDefault(False)
        self.pB_gotoend.setFlat(True)
        self.pB_gotoend.setObjectName("pB_gotoend")
        self.pB_pause = QtWidgets.QPushButton(self.tab_2)
        self.pB_pause.setGeometry(QtCore.QRect(140, 600, 25, 25))
        self.pB_pause.setAutoFillBackground(False)
        self.pB_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_pause.setIcon(icon1)
        self.pB_pause.setAutoDefault(False)
        self.pB_pause.setFlat(True)
        self.pB_pause.setObjectName("pB_pause")
        self.pB_play = QtWidgets.QPushButton(self.tab_2)
        self.pB_play.setGeometry(QtCore.QRect(80, 600, 25, 25))
        self.pB_play.setAutoFillBackground(False)
        self.pB_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_play.setIcon(icon2)
        self.pB_play.setAutoDefault(False)
        self.pB_play.setFlat(True)
        self.pB_play.setObjectName("pB_play")
        self.pB_backbegin = QtWidgets.QPushButton(self.tab_2)
        self.pB_backbegin.setGeometry(QtCore.QRect(50, 600, 25, 25))
        self.pB_backbegin.setAutoFillBackground(False)
        self.pB_backbegin.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon_begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_backbegin.setIcon(icon3)
        self.pB_backbegin.setAutoDefault(False)
        self.pB_backbegin.setFlat(True)
        self.pB_backbegin.setObjectName("pB_backbegin")
        self.pB_stop = QtWidgets.QPushButton(self.tab_2)
        self.pB_stop.setGeometry(QtCore.QRect(170, 600, 25, 25))
        self.pB_stop.setAutoFillBackground(False)
        self.pB_stop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_stop.setIcon(icon4)
        self.pB_stop.setAutoDefault(False)
        self.pB_stop.setFlat(True)
        self.pB_stop.setObjectName("pB_stop")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.scalePlot_vmax = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.scalePlot_vmax.setGeometry(QtCore.QRect(290, 50, 90, 20))
        self.scalePlot_vmax.setDecimals(4)
        self.scalePlot_vmax.setMinimum(-1000000000000000.0)
        self.scalePlot_vmax.setMaximum(1000000000000000.0)
        self.scalePlot_vmax.setObjectName("scalePlot_vmax")
        self.label_vmax = QtWidgets.QLabel(self.tab_6)
        self.label_vmax.setGeometry(QtCore.QRect(210, 50, 71, 20))
        self.label_vmax.setObjectName("label_vmax")
        self.label_vmin = QtWidgets.QLabel(self.tab_6)
        self.label_vmin.setGeometry(QtCore.QRect(210, 80, 71, 20))
        self.label_vmin.setObjectName("label_vmin")
        self.scalePlot_vmin = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.scalePlot_vmin.setGeometry(QtCore.QRect(290, 80, 90, 20))
        self.scalePlot_vmin.setDecimals(4)
        self.scalePlot_vmin.setMinimum(-1000000000000000.0)
        self.scalePlot_vmin.setMaximum(1000000000000000.0)
        self.scalePlot_vmin.setObjectName("scalePlot_vmin")
        self.normalize = QtWidgets.QCheckBox(self.tab_6)
        self.normalize.setGeometry(QtCore.QRect(210, 30, 127, 17))
        self.normalize.setObjectName("normalize")
        self.cB_verbose = QtWidgets.QCheckBox(self.tab_6)
        self.cB_verbose.setGeometry(QtCore.QRect(30, 360, 70, 16))
        self.cB_verbose.setObjectName("cB_verbose")
        self.label_vmax_9 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_9.setGeometry(QtCore.QRect(110, 410, 71, 20))
        self.label_vmax_9.setObjectName("label_vmax_9")
        self.eit_n = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_n.setGeometry(QtCore.QRect(190, 410, 90, 20))
        self.eit_n.setDecimals(0)
        self.eit_n.setMinimum(-1000000000000000.0)
        self.eit_n.setMaximum(1000000000000000.0)
        self.eit_n.setProperty("value", 64.0)
        self.eit_n.setObjectName("eit_n")
        self.pB_set_eit = QtWidgets.QPushButton(self.tab_6)
        self.pB_set_eit.setGeometry(QtCore.QRect(340, 360, 75, 23))
        self.pB_set_eit.setAutoFillBackground(False)
        self.pB_set_eit.setObjectName("pB_set_eit")
        self.label_vmax_7 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_7.setGeometry(QtCore.QRect(120, 350, 71, 20))
        self.label_vmax_7.setObjectName("label_vmax_7")
        self.eit_lamda = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_lamda.setGeometry(QtCore.QRect(200, 380, 90, 20))
        self.eit_lamda.setDecimals(4)
        self.eit_lamda.setMinimum(-1000000000000000.0)
        self.eit_lamda.setMaximum(1000000000000000.0)
        self.eit_lamda.setProperty("value", 0.01)
        self.eit_lamda.setObjectName("eit_lamda")
        self.label_vmax_8 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_8.setGeometry(QtCore.QRect(120, 380, 71, 20))
        self.label_vmax_8.setObjectName("label_vmax_8")
        self.eit_p = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_p.setGeometry(QtCore.QRect(200, 350, 90, 20))
        self.eit_p.setDecimals(1)
        self.eit_p.setMinimum(-1000000000000000.0)
        self.eit_p.setMaximum(1000000000000000.0)
        self.eit_p.setProperty("value", 0.5)
        self.eit_p.setObjectName("eit_p")
        self.cB_Image_fille_format = QtWidgets.QComboBox(self.tab_6)
        self.cB_Image_fille_format.setGeometry(QtCore.QRect(350, 220, 73, 20))
        self.cB_Image_fille_format.setCurrentText("")
        self.cB_Image_fille_format.setObjectName("cB_Image_fille_format")
        self.cB_Image_format = QtWidgets.QComboBox(self.tab_6)
        self.cB_Image_format.setGeometry(QtCore.QRect(270, 220, 73, 20))
        self.cB_Image_format.setCurrentText("")
        self.cB_Image_format.setObjectName("cB_Image_format")
        self.tabWidget.addTab(self.tab_6, "")
        self.DataSetName = QtWidgets.QLineEdit(self.centralwidget)
        self.DataSetName.setGeometry(QtCore.QRect(450, 20, 201, 20))
        self.DataSetName.setObjectName("DataSetName")
        self.progressBarFrame = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarFrame.setGeometry(QtCore.QRect(630, 50, 118, 23))
        self.progressBarFrame.setProperty("value", 0)
        self.progressBarFrame.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarFrame.setObjectName("progressBarFrame")
        self.actualFramecnt = QtWidgets.QSpinBox(self.centralwidget)
        self.actualFramecnt.setGeometry(QtCore.QRect(760, 20, 90, 20))
        self.actualFramecnt.setMaximum(255)
        self.actualFramecnt.setObjectName("actualFramecnt")
        self.label_actual_Frame_num = QtWidgets.QLabel(self.centralwidget)
        self.label_actual_Frame_num.setGeometry(QtCore.QRect(680, 20, 71, 20))
        self.label_actual_Frame_num.setObjectName("label_actual_Frame_num")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(440, 90, 661, 621))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 651, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.PlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.PlotLayout.setContentsMargins(0, 0, 0, 0)
        self.PlotLayout.setObjectName("PlotLayout")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_Z = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_Z.setGeometry(QtCore.QRect(0, 10, 661, 591))
        self.tabWidget_Z.setObjectName("tabWidget_Z")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidgetvoltages_Z = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetvoltages_Z.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z.setObjectName("tableWidgetvoltages_Z")
        self.tableWidgetvoltages_Z.setColumnCount(2)
        self.tableWidgetvoltages_Z.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidgetvoltages_Z_real = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidgetvoltages_Z_real.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z_real.setObjectName("tableWidgetvoltages_Z_real")
        self.tableWidgetvoltages_Z_real.setColumnCount(2)
        self.tableWidgetvoltages_Z_real.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidgetvoltages_Z_imag = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidgetvoltages_Z_imag.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z_imag.setObjectName("tableWidgetvoltages_Z_imag")
        self.tableWidgetvoltages_Z_imag.setColumnCount(2)
        self.tableWidgetvoltages_Z_imag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_Z.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_Z.addTab(self.tab_10, "")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.label_LiveView = QtWidgets.QLabel(self.centralwidget)
        self.label_LiveView.setGeometry(QtCore.QRect(800, 60, 47, 13))
        self.label_LiveView.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LiveView.setObjectName("label_LiveView")
        self.pB_Video = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Video.setGeometry(QtCore.QRect(1110, 70, 75, 23))
        self.pB_Video.setShortcut("")
        self.pB_Video.setCheckable(True)
        self.pB_Video.setChecked(False)
        self.pB_Video.setObjectName("pB_Video")
        self.video_frame = QtWidgets.QLabel(self.centralwidget)
        self.video_frame.setGeometry(QtCore.QRect(1110, 110, 800, 600))
        self.video_frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_frame.setMouseTracking(True)
        self.video_frame.setAutoFillBackground(False)
        self.video_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame.setObjectName("video_frame")
        self.video_frame_miniature = QtWidgets.QLabel(self.centralwidget)
        self.video_frame_miniature.setGeometry(QtCore.QRect(1600, 10, 300, 100))
        self.video_frame_miniature.setMouseTracking(False)
        self.video_frame_miniature.setAutoFillBackground(False)
        self.video_frame_miniature.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame_miniature.setObjectName("video_frame_miniature")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1934, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_Z.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_Start.setStatusTip(_translate("MainWindow", "Start measurement"))
        self.pB_Start.setText(_translate("MainWindow", "Start"))
        self.pB_Stop.setStatusTip(_translate("MainWindow", "Stop measurement"))
        self.pB_Stop.setText(_translate("MainWindow", "Stop"))
        self.pB_SaveSetup.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_SaveSetup.setText(_translate("MainWindow", "Save_Setup"))
        self.pB_connect.setStatusTip(_translate("MainWindow", "Connect to the selected serial port"))
        self.pB_connect.setText(_translate("MainWindow", "Connect"))
        self.status_device.setText(_translate("MainWindow", "Not Connected"))
        self.pB_LoadSetup.setStatusTip(_translate("MainWindow", "Load parameters from file (*.xlsx)"))
        self.pB_LoadSetup.setText(_translate("MainWindow", "Load_Setup"))
        self.cB_comport.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_refresh.setToolTip(_translate("MainWindow", "test"))
        self.pB_refresh.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pB_Set_Setup.setStatusTip(_translate("MainWindow", "Send measurements parameters to connected device"))
        self.pB_Set_Setup.setText(_translate("MainWindow", "Set_Setup"))
        self.label_Burst.setText(_translate("MainWindow", "Burst number"))
        self.label_minF.setText(_translate("MainWindow", "min Frequency [Hz]"))
        self.label_maxF.setText(_translate("MainWindow", "max Frequency [Hz]"))
        self.label_Steps.setText(_translate("MainWindow", "Steps number"))
        self.label_Burst_5.setText(_translate("MainWindow", "Scale"))
        self.label_FrameRate.setText(_translate("MainWindow", "Frame rate [fps]"))
        self.label_Current_Amplitude.setText(_translate("MainWindow", "Current Amplitude [mA]"))
        self.label_maxFrameRate.setText(_translate("MainWindow", "max Frame rate [fps]"))
        self.pB_disconnect.setStatusTip(_translate("MainWindow", "Disconnect the serial port"))
        self.pB_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label_ExcitationPattern.setText(_translate("MainWindow", "Excitation pattern"))
        item = self.Excitation_pattern.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Inj+ "))
        item = self.Excitation_pattern.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inj-"))
        self.pB_Get_Setup.setStatusTip(_translate("MainWindow", "Ask measurements parameters from connected device"))
        self.pB_Get_Setup.setText(_translate("MainWindow", "Get_Setup"))
        self.pB_Reset.setStatusTip(_translate("MainWindow", "Software reset of the device (reconnection needed after 10-15 sec)"))
        self.pB_Reset.setText(_translate("MainWindow", "Reset"))
        self.label_SN.setText(_translate("MainWindow", "S/N"))
        self.label_IP.setText(_translate("MainWindow", "IP Adress"))
        self.label_3.setText(_translate("MainWindow", "MAC Adress"))
        self.DHCP_Activated.setText(_translate("MainWindow", "DHCP_Activated"))
        self.Excitation_Stamp.setText(_translate("MainWindow", "Excitation_Stamp"))
        self.Current_Stamp.setText(_translate("MainWindow", "Current_Stamp"))
        self.Time_Stamp.setText(_translate("MainWindow", "Time_Stamp"))
        self.label_OutputConfig.setText(_translate("MainWindow", "Output config"))
        self.pB_loadinjpattern.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_loadinjpattern.setText(_translate("MainWindow", "Save_Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Setup EIT Device"))
        self.pB_ImagRec.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_ImagRec.setText(_translate("MainWindow", "Reconstruct"))
        self.pB_LoadDataSet.setStatusTip(_translate("MainWindow", "Load dataset from file (*.dat)"))
        self.pB_LoadDataSet.setText(_translate("MainWindow", "LoadDataSet"))
        self.pB_Plot.setStatusTip(_translate("MainWindow", "Plot....."))
        self.pB_Plot.setText(_translate("MainWindow", "Plot"))
        self.pB_Uplot.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.label_Frame_indx.setText(_translate("MainWindow", "Actual Frame#"))
        self.showReal.setText(_translate("MainWindow", "Real"))
        self.showImag.setText(_translate("MainWindow", "Image"))
        self.showPhase.setText(_translate("MainWindow", "Phase"))
        self.showAbsValue.setText(_translate("MainWindow", "Show absolute values"))
        self.showMagnitude.setText(_translate("MainWindow", "Magnitude"))
        self.label_vmax_2.setText(_translate("MainWindow", "in Hz"))
        self.rB_TimeDiff.setText(_translate("MainWindow", "Time-difference"))
        self.rB_FreqDiff.setText(_translate("MainWindow", "Frequency-difference"))
        self.pB_UpdateRef4TD.setStatusTip(_translate("MainWindow", "Start measurement"))
        self.pB_UpdateRef4TD.setText(_translate("MainWindow", "Ref"))
        self.rB_RawData.setText(_translate("MainWindow", "Single Meas. (absolut)"))
        self.label_vmax_4.setText(_translate("MainWindow", "in Hz"))
        self.label_vmax_3.setText(_translate("MainWindow", "in Hz"))
        self.label_vmax_5.setText(_translate("MainWindow", "in Hz"))
        self.rB_plot_graph.setText(_translate("MainWindow", "Graph"))
        self.rB_Image.setText(_translate("MainWindow", "Image"))
        self.label_vmax_6.setText(_translate("MainWindow", "Reconstruction"))
        self.checkB_diff.setText(_translate("MainWindow", "Difference"))
        self.checkB_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.pB_loadRef.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_loadRef.setText(_translate("MainWindow", "loadref"))
        self.checkB_YLog.setText(_translate("MainWindow", "y log"))
        self.label_FEMRefinement.setText(_translate("MainWindow", "FEM Refinement"))
        self.label_replay_refresh_time.setText(_translate("MainWindow", "Refresh time [s]"))
        self.pB_gotoend.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_pause.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_play.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_backbegin.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_stop.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Meas"))
        self.label_vmax.setText(_translate("MainWindow", "vmax"))
        self.label_vmin.setText(_translate("MainWindow", "vmin"))
        self.normalize.setText(_translate("MainWindow", "Normalize"))
        self.cB_verbose.setText(_translate("MainWindow", "verbose"))
        self.label_vmax_9.setText(_translate("MainWindow", "n"))
        self.pB_set_eit.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_set_eit.setText(_translate("MainWindow", "set EIT"))
        self.label_vmax_7.setText(_translate("MainWindow", "p"))
        self.label_vmax_8.setText(_translate("MainWindow", "lamda"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "EIT Plotter"))
        self.DataSetName.setText(_translate("MainWindow", "DataSetName_default"))
        self.label_actual_Frame_num.setText(_translate("MainWindow", "Frame number"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Graph"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_3), _translate("MainWindow", "Z"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_4), _translate("MainWindow", "Real"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_5), _translate("MainWindow", "Imag"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_9), _translate("MainWindow", "Magnitude"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_10), _translate("MainWindow", "Phase"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Tables"))
        self.label_LiveView.setText(_translate("MainWindow", "Live"))
        self.pB_Video.setText(_translate("MainWindow", "Video"))
        self.video_frame.setText(_translate("MainWindow", "Live Video"))
        self.video_frame_miniature.setText(_translate("MainWindow", "Live Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
