# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditlog = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditlog.setGeometry(QtCore.QRect(10, 730, 411, 161))
        self.textEditlog.setObjectName("textEditlog")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 431, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pB_save_setup = QtWidgets.QPushButton(self.tab)
        self.pB_save_setup.setGeometry(QtCore.QRect(340, 110, 75, 23))
        self.pB_save_setup.setAutoFillBackground(False)
        self.pB_save_setup.setObjectName("pB_save_setup")
        self.pB_connect = QtWidgets.QPushButton(self.tab)
        self.pB_connect.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.pB_connect.setAutoFillBackground(False)
        self.pB_connect.setObjectName("pB_connect")
        self.lab_device_status = QtWidgets.QLabel(self.tab)
        self.lab_device_status.setGeometry(QtCore.QRect(10, 80, 381, 16))
        self.lab_device_status.setStatusTip("")
        self.lab_device_status.setAutoFillBackground(True)
        self.lab_device_status.setObjectName("lab_device_status")
        self.pB_load_setup = QtWidgets.QPushButton(self.tab)
        self.pB_load_setup.setGeometry(QtCore.QRect(260, 110, 75, 23))
        self.pB_load_setup.setAutoFillBackground(False)
        self.pB_load_setup.setObjectName("pB_load_setup")
        self.cB_ports = QtWidgets.QComboBox(self.tab)
        self.cB_ports.setGeometry(QtCore.QRect(10, 50, 381, 22))
        self.cB_ports.setToolTip("")
        self.cB_ports.setObjectName("cB_ports")
        self.pB_refresh = QtWidgets.QPushButton(self.tab)
        self.pB_refresh.setEnabled(True)
        self.pB_refresh.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pB_refresh.setAutoFillBackground(False)
        self.pB_refresh.setObjectName("pB_refresh")
        self.pB_set_setup = QtWidgets.QPushButton(self.tab)
        self.pB_set_setup.setEnabled(True)
        self.pB_set_setup.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pB_set_setup.setAutoFillBackground(False)
        self.pB_set_setup.setObjectName("pB_set_setup")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 211, 204))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.LayoutParameters = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.LayoutParameters.setContentsMargins(0, 0, 0, 0)
        self.LayoutParameters.setHorizontalSpacing(6)
        self.LayoutParameters.setObjectName("LayoutParameters")
        self.sBd_exc_amp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_exc_amp.setDecimals(4)
        self.sBd_exc_amp.setMinimum(0.0001)
        self.sBd_exc_amp.setMaximum(10.0)
        self.sBd_exc_amp.setSingleStep(0.1)
        self.sBd_exc_amp.setObjectName("sBd_exc_amp")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBd_exc_amp)
        self.label_Burst = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst.setObjectName("label_Burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Burst)
        self.sB_burst = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_burst.setMaximum(255)
        self.sB_burst.setObjectName("sB_burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_burst)
        self.label_minF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_minF.setObjectName("label_minF")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_minF)
        self.label_maxF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxF.setObjectName("label_maxF")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_maxF)
        self.label_Steps = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Steps.setObjectName("label_Steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Steps)
        self.sB_freq_steps = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_freq_steps.setMaximum(255)
        self.sB_freq_steps.setObjectName("sB_freq_steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sB_freq_steps)
        self.label_Burst_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst_5.setObjectName("label_Burst_5")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_Burst_5)
        self.cB_scale = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cB_scale.setEditable(False)
        self.cB_scale.setMaxVisibleItems(2)
        self.cB_scale.setObjectName("cB_scale")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cB_scale)
        self.label_FrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_FrameRate.setObjectName("label_FrameRate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_FrameRate)
        self.sBd_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_frame_rate.setDecimals(3)
        self.sBd_frame_rate.setMaximum(100.0)
        self.sBd_frame_rate.setSingleStep(0.001)
        self.sBd_frame_rate.setObjectName("sBd_frame_rate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sBd_frame_rate)
        self.label_Current_Amplitude = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Current_Amplitude.setObjectName("label_Current_Amplitude")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Current_Amplitude)
        self.sBd_freq_max = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_max.setAutoFillBackground(False)
        self.sBd_freq_max.setMinimum(100.0)
        self.sBd_freq_max.setMaximum(1000000.0)
        self.sBd_freq_max.setObjectName("sBd_freq_max")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_max)
        self.sBd_freq_min = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_min.setMinimum(100.0)
        self.sBd_freq_min.setMaximum(1000000.0)
        self.sBd_freq_min.setObjectName("sBd_freq_min")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_min)
        self.sBd_max_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_max_frame_rate.setEnabled(False)
        self.sBd_max_frame_rate.setDecimals(3)
        self.sBd_max_frame_rate.setMaximum(100.0)
        self.sBd_max_frame_rate.setSingleStep(0.001)
        self.sBd_max_frame_rate.setObjectName("sBd_max_frame_rate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sBd_max_frame_rate)
        self.label_maxFrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxFrameRate.setObjectName("label_maxFrameRate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_maxFrameRate)
        self.pB_disconnect = QtWidgets.QPushButton(self.tab)
        self.pB_disconnect.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.pB_disconnect.setToolTip("")
        self.pB_disconnect.setAutoFillBackground(False)
        self.pB_disconnect.setObjectName("pB_disconnect")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 150, 121, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayoutExcitationPattern = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayoutExcitationPattern.setContentsMargins(0, 0, 0, 0)
        self.vLayoutExcitationPattern.setObjectName("vLayoutExcitationPattern")
        self.label_ExcitationPattern = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ExcitationPattern.setObjectName("label_ExcitationPattern")
        self.vLayoutExcitationPattern.addWidget(self.label_ExcitationPattern)
        self.tw_exc_pattern = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tw_exc_pattern.setObjectName("tw_exc_pattern")
        self.tw_exc_pattern.setColumnCount(2)
        self.tw_exc_pattern.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_pattern.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_pattern.setHorizontalHeaderItem(1, item)
        self.tw_exc_pattern.horizontalHeader().setDefaultSectionSize(40)
        self.vLayoutExcitationPattern.addWidget(self.tw_exc_pattern)
        self.pB_get_setup = QtWidgets.QPushButton(self.tab)
        self.pB_get_setup.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.pB_get_setup.setAutoFillBackground(False)
        self.pB_get_setup.setObjectName("pB_get_setup")
        self.pB_reset = QtWidgets.QPushButton(self.tab)
        self.pB_reset.setGeometry(QtCore.QRect(170, 110, 75, 23))
        self.pB_reset.setAutoFillBackground(False)
        self.pB_reset.setObjectName("pB_reset")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 400, 201, 166))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LayoutComConfig = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.LayoutComConfig.setContentsMargins(0, 0, 0, 0)
        self.LayoutComConfig.setObjectName("LayoutComConfig")
        self.label_SN = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_SN.setObjectName("label_SN")
        self.LayoutComConfig.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_SN)
        self.lE_sn = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lE_sn.setEnabled(False)
        self.lE_sn.setToolTip("")
        self.lE_sn.setWhatsThis("")
        self.lE_sn.setInputMask("")
        self.lE_sn.setFrame(True)
        self.lE_sn.setObjectName("lE_sn")
        self.LayoutComConfig.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lE_sn)
        self.label_IP = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_IP.setObjectName("label_IP")
        self.LayoutComConfig.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_IP)
        self.lE_ip = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lE_ip.setToolTip("")
        self.lE_ip.setWhatsThis("")
        self.lE_ip.setInputMask("")
        self.lE_ip.setFrame(True)
        self.lE_ip.setObjectName("lE_ip")
        self.LayoutComConfig.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lE_ip)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.LayoutComConfig.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lE_mac = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lE_mac.setEnabled(False)
        self.lE_mac.setObjectName("lE_mac")
        self.LayoutComConfig.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lE_mac)
        self.chB_dhcp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chB_dhcp.setEnabled(False)
        self.chB_dhcp.setChecked(False)
        self.chB_dhcp.setObjectName("chB_dhcp")
        self.LayoutComConfig.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chB_dhcp)
        self.chB_exc_stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chB_exc_stamp.setEnabled(False)
        self.chB_exc_stamp.setChecked(True)
        self.chB_exc_stamp.setObjectName("chB_exc_stamp")
        self.LayoutComConfig.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chB_exc_stamp)
        self.chB_current_stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chB_current_stamp.setEnabled(False)
        self.chB_current_stamp.setChecked(True)
        self.chB_current_stamp.setObjectName("chB_current_stamp")
        self.LayoutComConfig.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chB_current_stamp)
        self.chB_time_stamp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chB_time_stamp.setEnabled(False)
        self.chB_time_stamp.setChecked(True)
        self.chB_time_stamp.setObjectName("chB_time_stamp")
        self.LayoutComConfig.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.chB_time_stamp)
        self.label_OutputConfig = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_OutputConfig.setObjectName("label_OutputConfig")
        self.LayoutComConfig.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_OutputConfig)
        self.pB_load_exc_pattern = QtWidgets.QPushButton(self.tab)
        self.pB_load_exc_pattern.setGeometry(QtCore.QRect(240, 580, 131, 23))
        self.pB_load_exc_pattern.setAutoFillBackground(False)
        self.pB_load_exc_pattern.setObjectName("pB_load_exc_pattern")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pB_reconstruction = QtWidgets.QPushButton(self.tab_2)
        self.pB_reconstruction.setGeometry(QtCore.QRect(340, 340, 75, 23))
        self.pB_reconstruction.setAutoFillBackground(False)
        self.pB_reconstruction.setObjectName("pB_reconstruction")
        self.pB_load_meas_dataset = QtWidgets.QPushButton(self.tab_2)
        self.pB_load_meas_dataset.setGeometry(QtCore.QRect(330, 90, 75, 23))
        self.pB_load_meas_dataset.setAutoFillBackground(False)
        self.pB_load_meas_dataset.setObjectName("pB_load_meas_dataset")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 90, 301, 211))
        self.textEdit.setObjectName("textEdit")
        self.pB_Plot = QtWidgets.QPushButton(self.tab_2)
        self.pB_Plot.setGeometry(QtCore.QRect(340, 300, 75, 23))
        self.pB_Plot.setAutoFillBackground(False)
        self.pB_Plot.setObjectName("pB_Plot")
        self.pB_Uplot = QtWidgets.QPushButton(self.tab_2)
        self.pB_Uplot.setGeometry(QtCore.QRect(340, 270, 75, 23))
        self.pB_Uplot.setAutoFillBackground(False)
        self.pB_Uplot.setObjectName("pB_Uplot")
        self.cB_Frame_indx = QtWidgets.QComboBox(self.tab_2)
        self.cB_Frame_indx.setGeometry(QtCore.QRect(340, 190, 69, 22))
        self.cB_Frame_indx.setObjectName("cB_Frame_indx")
        self.label_Frame_indx = QtWidgets.QLabel(self.tab_2)
        self.label_Frame_indx.setGeometry(QtCore.QRect(340, 150, 91, 31))
        self.label_Frame_indx.setObjectName("label_Frame_indx")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 500, 260, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showReal = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showReal.setChecked(True)
        self.showReal.setObjectName("showReal")
        self.gridLayout_2.addWidget(self.showReal, 0, 0, 1, 1)
        self.showImag = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showImag.setObjectName("showImag")
        self.gridLayout_2.addWidget(self.showImag, 1, 0, 1, 1)
        self.showPhase = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showPhase.setObjectName("showPhase")
        self.gridLayout_2.addWidget(self.showPhase, 1, 1, 1, 1)
        self.showAbsValue = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.showAbsValue.setObjectName("showAbsValue")
        self.gridLayout_2.addWidget(self.showAbsValue, 2, 0, 1, 1)
        self.showMagnitude = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.showMagnitude.setObjectName("showMagnitude")
        self.gridLayout_2.addWidget(self.showMagnitude, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 405, 345, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_vmax_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_2.setObjectName("label_vmax_2")
        self.gridLayout.addWidget(self.label_vmax_2, 0, 2, 1, 1)
        self.rB_time_diff_meas = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_time_diff_meas.setObjectName("rB_time_diff_meas")
        self.gridLayout.addWidget(self.rB_time_diff_meas, 1, 0, 1, 1)
        self.rB_freq_diff_meas = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_freq_diff_meas.setObjectName("rB_freq_diff_meas")
        self.gridLayout.addWidget(self.rB_freq_diff_meas, 2, 0, 1, 1)
        self.cB_freq_freq_meas_0 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_freq_freq_meas_0.setCurrentText("")
        self.cB_freq_freq_meas_0.setObjectName("cB_freq_freq_meas_0")
        self.gridLayout.addWidget(self.cB_freq_freq_meas_0, 2, 1, 1, 1)
        self.cB_freq_freq_meas_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_freq_freq_meas_1.setObjectName("cB_freq_freq_meas_1")
        self.gridLayout.addWidget(self.cB_freq_freq_meas_1, 2, 3, 1, 1)
        self.rB_abs_meas = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rB_abs_meas.setChecked(True)
        self.rB_abs_meas.setObjectName("rB_abs_meas")
        self.gridLayout.addWidget(self.rB_abs_meas, 0, 0, 1, 1)
        self.label_vmax_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_4.setObjectName("label_vmax_4")
        self.gridLayout.addWidget(self.label_vmax_4, 2, 2, 1, 1)
        self.label_vmax_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_3.setObjectName("label_vmax_3")
        self.gridLayout.addWidget(self.label_vmax_3, 1, 2, 1, 1)
        self.label_vmax_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vmax_5.setObjectName("label_vmax_5")
        self.gridLayout.addWidget(self.label_vmax_5, 2, 4, 1, 1)
        self.pB_set_ref_time_diff = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pB_set_ref_time_diff.setAutoFillBackground(False)
        self.pB_set_ref_time_diff.setObjectName("pB_set_ref_time_diff")
        self.gridLayout.addWidget(self.pB_set_ref_time_diff, 1, 3, 1, 1)
        self.cB_freq_abs_meas = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_freq_abs_meas.setObjectName("cB_freq_abs_meas")
        self.gridLayout.addWidget(self.cB_freq_abs_meas, 0, 1, 1, 1)
        self.cB_freq_time_meas = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_freq_time_meas.setCurrentText("")
        self.cB_freq_time_meas.setObjectName("cB_freq_time_meas")
        self.gridLayout.addWidget(self.cB_freq_time_meas, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 310, 220, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cB_rec_method = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cB_rec_method.setObjectName("cB_rec_method")
        self.gridLayout_3.addWidget(self.cB_rec_method, 1, 2, 1, 1)
        self.label_vmax_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vmax_6.setObjectName("label_vmax_6")
        self.gridLayout_3.addWidget(self.label_vmax_6, 1, 1, 1, 1)
        self.chB_diff = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chB_diff.setObjectName("chB_diff")
        self.gridLayout_3.addWidget(self.chB_diff, 0, 2, 1, 1)
        self.chB_Uplot = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chB_Uplot.setObjectName("chB_Uplot")
        self.gridLayout_3.addWidget(self.chB_Uplot, 0, 1, 1, 1)
        self.chB_plot_image_rec = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chB_plot_image_rec.setObjectName("chB_plot_image_rec")
        self.gridLayout_3.addWidget(self.chB_plot_image_rec, 1, 0, 1, 1)
        self.chB_plot_graph = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chB_plot_graph.setChecked(True)
        self.chB_plot_graph.setObjectName("chB_plot_graph")
        self.gridLayout_3.addWidget(self.chB_plot_graph, 0, 0, 1, 1)
        self.pB_loadRef = QtWidgets.QPushButton(self.tab_2)
        self.pB_loadRef.setGeometry(QtCore.QRect(340, 230, 75, 23))
        self.pB_loadRef.setAutoFillBackground(False)
        self.pB_loadRef.setObjectName("pB_loadRef")
        self.chB_y_log = QtWidgets.QCheckBox(self.tab_2)
        self.chB_y_log.setGeometry(QtCore.QRect(330, 540, 72, 17))
        self.chB_y_log.setObjectName("chB_y_log")
        self.eit_FEMRefinement = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.eit_FEMRefinement.setGeometry(QtCore.QRect(250, 370, 90, 20))
        self.eit_FEMRefinement.setDecimals(4)
        self.eit_FEMRefinement.setMinimum(0.0)
        self.eit_FEMRefinement.setMaximum(10.0)
        self.eit_FEMRefinement.setSingleStep(0.001)
        self.eit_FEMRefinement.setProperty("value", 0.1)
        self.eit_FEMRefinement.setObjectName("eit_FEMRefinement")
        self.label_FEMRefinement = QtWidgets.QLabel(self.tab_2)
        self.label_FEMRefinement.setGeometry(QtCore.QRect(250, 350, 91, 20))
        self.label_FEMRefinement.setObjectName("label_FEMRefinement")
        self.replay_refresh_time = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.replay_refresh_time.setGeometry(QtCore.QRect(290, 600, 90, 20))
        self.replay_refresh_time.setDecimals(1)
        self.replay_refresh_time.setMinimum(1.0)
        self.replay_refresh_time.setMaximum(10.0)
        self.replay_refresh_time.setSingleStep(1.0)
        self.replay_refresh_time.setProperty("value", 1.0)
        self.replay_refresh_time.setObjectName("replay_refresh_time")
        self.label_replay_refresh_time = QtWidgets.QLabel(self.tab_2)
        self.label_replay_refresh_time.setGeometry(QtCore.QRect(290, 580, 91, 20))
        self.label_replay_refresh_time.setObjectName("label_replay_refresh_time")
        self.slider_replay_meas = QtWidgets.QSlider(self.tab_2)
        self.slider_replay_meas.setGeometry(QtCore.QRect(10, 640, 391, 22))
        self.slider_replay_meas.setOrientation(QtCore.Qt.Horizontal)
        self.slider_replay_meas.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_replay_meas.setTickInterval(0)
        self.slider_replay_meas.setObjectName("slider_replay_meas")
        self.pB_gotoend_replay_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_gotoend_replay_meas.setGeometry(QtCore.QRect(110, 600, 25, 25))
        self.pB_gotoend_replay_meas.setAutoFillBackground(False)
        self.pB_gotoend_replay_meas.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("docs/icons/icon_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_gotoend_replay_meas.setIcon(icon)
        self.pB_gotoend_replay_meas.setAutoDefault(False)
        self.pB_gotoend_replay_meas.setFlat(True)
        self.pB_gotoend_replay_meas.setObjectName("pB_gotoend_replay_meas")
        self.pB_pause_replay_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_pause_replay_meas.setGeometry(QtCore.QRect(140, 600, 25, 25))
        self.pB_pause_replay_meas.setAutoFillBackground(False)
        self.pB_pause_replay_meas.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("docs/icons/icon_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_pause_replay_meas.setIcon(icon1)
        self.pB_pause_replay_meas.setAutoDefault(False)
        self.pB_pause_replay_meas.setFlat(True)
        self.pB_pause_replay_meas.setObjectName("pB_pause_replay_meas")
        self.pB_play_replay_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_play_replay_meas.setGeometry(QtCore.QRect(80, 600, 25, 25))
        self.pB_play_replay_meas.setAutoFillBackground(False)
        self.pB_play_replay_meas.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("docs/icons/icon_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_play_replay_meas.setIcon(icon2)
        self.pB_play_replay_meas.setAutoDefault(False)
        self.pB_play_replay_meas.setFlat(True)
        self.pB_play_replay_meas.setObjectName("pB_play_replay_meas")
        self.pB_backbegin_replay_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_backbegin_replay_meas.setGeometry(QtCore.QRect(50, 600, 25, 25))
        self.pB_backbegin_replay_meas.setAutoFillBackground(False)
        self.pB_backbegin_replay_meas.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("docs/icons/icon_begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_backbegin_replay_meas.setIcon(icon3)
        self.pB_backbegin_replay_meas.setAutoDefault(False)
        self.pB_backbegin_replay_meas.setFlat(True)
        self.pB_backbegin_replay_meas.setObjectName("pB_backbegin_replay_meas")
        self.pB_stop_replay_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_stop_replay_meas.setGeometry(QtCore.QRect(170, 600, 25, 25))
        self.pB_stop_replay_meas.setAutoFillBackground(False)
        self.pB_stop_replay_meas.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("docs/icons/icon_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_stop_replay_meas.setIcon(icon4)
        self.pB_stop_replay_meas.setAutoDefault(False)
        self.pB_stop_replay_meas.setFlat(True)
        self.pB_stop_replay_meas.setObjectName("pB_stop_replay_meas")
        self.lab_live_view = QtWidgets.QLabel(self.tab_2)
        self.lab_live_view.setGeometry(QtCore.QRect(340, 50, 47, 13))
        self.lab_live_view.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_live_view.setObjectName("lab_live_view")
        self.sB_actual_frame_cnt = QtWidgets.QSpinBox(self.tab_2)
        self.sB_actual_frame_cnt.setGeometry(QtCore.QRect(350, 10, 51, 20))
        self.sB_actual_frame_cnt.setMaximum(255)
        self.sB_actual_frame_cnt.setObjectName("sB_actual_frame_cnt")
        self.lab_actual_frame_cnt = QtWidgets.QLabel(self.tab_2)
        self.lab_actual_frame_cnt.setGeometry(QtCore.QRect(230, 10, 111, 20))
        self.lab_actual_frame_cnt.setObjectName("lab_actual_frame_cnt")
        self.meas_dataset_name = QtWidgets.QLineEdit(self.tab_2)
        self.meas_dataset_name.setGeometry(QtCore.QRect(20, 10, 201, 20))
        self.meas_dataset_name.setObjectName("meas_dataset_name")
        self.meas_progress_bar = QtWidgets.QProgressBar(self.tab_2)
        self.meas_progress_bar.setGeometry(QtCore.QRect(200, 40, 118, 23))
        self.meas_progress_bar.setProperty("value", 0)
        self.meas_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.meas_progress_bar.setObjectName("meas_progress_bar")
        self.pB_stop_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_stop_meas.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.pB_stop_meas.setAutoFillBackground(False)
        self.pB_stop_meas.setObjectName("pB_stop_meas")
        self.pB_start_meas = QtWidgets.QPushButton(self.tab_2)
        self.pB_start_meas.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.pB_start_meas.setAutoFillBackground(False)
        self.pB_start_meas.setObjectName("pB_start_meas")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.scalePlot_vmax = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.scalePlot_vmax.setGeometry(QtCore.QRect(290, 50, 90, 20))
        self.scalePlot_vmax.setDecimals(4)
        self.scalePlot_vmax.setMinimum(-1000000000000000.0)
        self.scalePlot_vmax.setMaximum(1000000000000000.0)
        self.scalePlot_vmax.setObjectName("scalePlot_vmax")
        self.label_vmax = QtWidgets.QLabel(self.tab_6)
        self.label_vmax.setGeometry(QtCore.QRect(210, 50, 71, 20))
        self.label_vmax.setObjectName("label_vmax")
        self.label_vmin = QtWidgets.QLabel(self.tab_6)
        self.label_vmin.setGeometry(QtCore.QRect(210, 80, 71, 20))
        self.label_vmin.setObjectName("label_vmin")
        self.scalePlot_vmin = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.scalePlot_vmin.setGeometry(QtCore.QRect(290, 80, 90, 20))
        self.scalePlot_vmin.setDecimals(4)
        self.scalePlot_vmin.setMinimum(-1000000000000000.0)
        self.scalePlot_vmin.setMaximum(1000000000000000.0)
        self.scalePlot_vmin.setObjectName("scalePlot_vmin")
        self.normalize = QtWidgets.QCheckBox(self.tab_6)
        self.normalize.setGeometry(QtCore.QRect(210, 30, 127, 17))
        self.normalize.setObjectName("normalize")
        self.cB_verbose = QtWidgets.QCheckBox(self.tab_6)
        self.cB_verbose.setGeometry(QtCore.QRect(30, 360, 70, 16))
        self.cB_verbose.setObjectName("cB_verbose")
        self.label_vmax_9 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_9.setGeometry(QtCore.QRect(110, 410, 71, 20))
        self.label_vmax_9.setObjectName("label_vmax_9")
        self.eit_n = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_n.setGeometry(QtCore.QRect(190, 410, 90, 20))
        self.eit_n.setDecimals(0)
        self.eit_n.setMinimum(-1000000000000000.0)
        self.eit_n.setMaximum(1000000000000000.0)
        self.eit_n.setProperty("value", 64.0)
        self.eit_n.setObjectName("eit_n")
        self.pB_set_eit = QtWidgets.QPushButton(self.tab_6)
        self.pB_set_eit.setGeometry(QtCore.QRect(340, 360, 75, 23))
        self.pB_set_eit.setAutoFillBackground(False)
        self.pB_set_eit.setObjectName("pB_set_eit")
        self.label_vmax_7 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_7.setGeometry(QtCore.QRect(120, 350, 71, 20))
        self.label_vmax_7.setObjectName("label_vmax_7")
        self.eit_lamda = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_lamda.setGeometry(QtCore.QRect(200, 380, 90, 20))
        self.eit_lamda.setDecimals(4)
        self.eit_lamda.setMinimum(-1000000000000000.0)
        self.eit_lamda.setMaximum(1000000000000000.0)
        self.eit_lamda.setProperty("value", 0.01)
        self.eit_lamda.setObjectName("eit_lamda")
        self.label_vmax_8 = QtWidgets.QLabel(self.tab_6)
        self.label_vmax_8.setGeometry(QtCore.QRect(120, 380, 71, 20))
        self.label_vmax_8.setObjectName("label_vmax_8")
        self.eit_p = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.eit_p.setGeometry(QtCore.QRect(200, 350, 90, 20))
        self.eit_p.setDecimals(1)
        self.eit_p.setMinimum(-1000000000000000.0)
        self.eit_p.setMaximum(1000000000000000.0)
        self.eit_p.setProperty("value", 0.5)
        self.eit_p.setObjectName("eit_p")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.cB_video_devices = QtWidgets.QComboBox(self.tab_11)
        self.cB_video_devices.setGeometry(QtCore.QRect(90, 30, 81, 22))
        self.cB_video_devices.setToolTip("")
        self.cB_video_devices.setEditable(False)
        self.cB_video_devices.setObjectName("cB_video_devices")
        self.pB_refresh_video_devices = QtWidgets.QPushButton(self.tab_11)
        self.pB_refresh_video_devices.setEnabled(True)
        self.pB_refresh_video_devices.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.pB_refresh_video_devices.setAutoFillBackground(False)
        self.pB_refresh_video_devices.setObjectName("pB_refresh_video_devices")
        self.pB_start_video = QtWidgets.QPushButton(self.tab_11)
        self.pB_start_video.setGeometry(QtCore.QRect(190, 70, 75, 23))
        self.pB_start_video.setShortcut("")
        self.pB_start_video.setCheckable(True)
        self.pB_start_video.setChecked(False)
        self.pB_start_video.setObjectName("pB_start_video")
        self.cB_img_file_ext = QtWidgets.QComboBox(self.tab_11)
        self.cB_img_file_ext.setGeometry(QtCore.QRect(260, 180, 73, 20))
        self.cB_img_file_ext.setCurrentText("")
        self.cB_img_file_ext.setObjectName("cB_img_file_ext")
        self.cB_img_size = QtWidgets.QComboBox(self.tab_11)
        self.cB_img_size.setGeometry(QtCore.QRect(170, 180, 73, 20))
        self.cB_img_size.setCurrentText("")
        self.cB_img_size.setObjectName("cB_img_size")
        self.tabWidget.addTab(self.tab_11, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(440, 100, 661, 621))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 651, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.PlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.PlotLayout.setContentsMargins(0, 0, 0, 0)
        self.PlotLayout.setObjectName("PlotLayout")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_Z = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_Z.setGeometry(QtCore.QRect(0, 10, 661, 591))
        self.tabWidget_Z.setObjectName("tabWidget_Z")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidgetvoltages_Z = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetvoltages_Z.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z.setObjectName("tableWidgetvoltages_Z")
        self.tableWidgetvoltages_Z.setColumnCount(2)
        self.tableWidgetvoltages_Z.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidgetvoltages_Z_real = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidgetvoltages_Z_real.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z_real.setObjectName("tableWidgetvoltages_Z_real")
        self.tableWidgetvoltages_Z_real.setColumnCount(2)
        self.tableWidgetvoltages_Z_real.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidgetvoltages_Z_imag = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidgetvoltages_Z_imag.setGeometry(QtCore.QRect(0, 10, 651, 551))
        self.tableWidgetvoltages_Z_imag.setObjectName("tableWidgetvoltages_Z_imag")
        self.tableWidgetvoltages_Z_imag.setColumnCount(2)
        self.tableWidgetvoltages_Z_imag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(1, item)
        self.tabWidget_Z.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_Z.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_Z.addTab(self.tab_10, "")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.video_frame = QtWidgets.QLabel(self.tab_12)
        self.video_frame.setGeometry(QtCore.QRect(0, 10, 651, 581))
        self.video_frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_frame.setMouseTracking(True)
        self.video_frame.setAutoFillBackground(False)
        self.video_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame.setObjectName("video_frame")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.video_frame_miniature = QtWidgets.QLabel(self.centralwidget)
        self.video_frame_miniature.setGeometry(QtCore.QRect(890, 0, 201, 100))
        self.video_frame_miniature.setMouseTracking(False)
        self.video_frame_miniature.setAutoFillBackground(False)
        self.video_frame_miniature.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame_miniature.setObjectName("video_frame_miniature")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabWidget_Z.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_save_setup.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_save_setup.setText(_translate("MainWindow", "Save_Setup"))
        self.pB_connect.setStatusTip(_translate("MainWindow", "Connect to the selected serial port"))
        self.pB_connect.setText(_translate("MainWindow", "Connect"))
        self.lab_device_status.setText(_translate("MainWindow", "Not Connected"))
        self.pB_load_setup.setStatusTip(_translate("MainWindow", "Load parameters from file (*.xlsx)"))
        self.pB_load_setup.setText(_translate("MainWindow", "Load_Setup"))
        self.cB_ports.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_refresh.setToolTip(_translate("MainWindow", "test"))
        self.pB_refresh.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pB_set_setup.setStatusTip(_translate("MainWindow", "Send measurements parameters to connected device"))
        self.pB_set_setup.setText(_translate("MainWindow", "Set_Setup"))
        self.label_Burst.setText(_translate("MainWindow", "Burst number"))
        self.label_minF.setText(_translate("MainWindow", "min Frequency [Hz]"))
        self.label_maxF.setText(_translate("MainWindow", "max Frequency [Hz]"))
        self.label_Steps.setText(_translate("MainWindow", "Steps number"))
        self.label_Burst_5.setText(_translate("MainWindow", "Scale"))
        self.label_FrameRate.setText(_translate("MainWindow", "Frame rate [fps]"))
        self.label_Current_Amplitude.setText(_translate("MainWindow", "Current Amplitude [mA]"))
        self.label_maxFrameRate.setText(_translate("MainWindow", "max Frame rate [fps]"))
        self.pB_disconnect.setStatusTip(_translate("MainWindow", "Disconnect the serial port"))
        self.pB_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label_ExcitationPattern.setText(_translate("MainWindow", "Excitation pattern"))
        item = self.tw_exc_pattern.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Inj+ "))
        item = self.tw_exc_pattern.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inj-"))
        self.pB_get_setup.setStatusTip(_translate("MainWindow", "Ask measurements parameters from connected device"))
        self.pB_get_setup.setText(_translate("MainWindow", "Get_Setup"))
        self.pB_reset.setStatusTip(_translate("MainWindow", "Software reset of the device (reconnection needed after 10-15 sec)"))
        self.pB_reset.setText(_translate("MainWindow", "Reset"))
        self.label_SN.setText(_translate("MainWindow", "S/N"))
        self.label_IP.setText(_translate("MainWindow", "IP Adress"))
        self.label_3.setText(_translate("MainWindow", "MAC Adress"))
        self.chB_dhcp.setText(_translate("MainWindow", "DHCP_Activated"))
        self.chB_exc_stamp.setText(_translate("MainWindow", "Excitation_Stamp"))
        self.chB_current_stamp.setText(_translate("MainWindow", "Current_Stamp"))
        self.chB_time_stamp.setText(_translate("MainWindow", "Time_Stamp"))
        self.label_OutputConfig.setText(_translate("MainWindow", "Output config"))
        self.pB_load_exc_pattern.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_load_exc_pattern.setText(_translate("MainWindow", "Load Excitation Pattern"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Device"))
        self.pB_reconstruction.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_reconstruction.setText(_translate("MainWindow", "Reconstruct"))
        self.pB_load_meas_dataset.setStatusTip(_translate("MainWindow", "Load dataset from file (*.dat)"))
        self.pB_load_meas_dataset.setText(_translate("MainWindow", "LoadDataSet"))
        self.pB_Plot.setStatusTip(_translate("MainWindow", "Plot....."))
        self.pB_Plot.setText(_translate("MainWindow", "Plot"))
        self.pB_Uplot.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.label_Frame_indx.setText(_translate("MainWindow", "Actual Frame#"))
        self.showReal.setText(_translate("MainWindow", "Real"))
        self.showImag.setText(_translate("MainWindow", "Image"))
        self.showPhase.setText(_translate("MainWindow", "Phase"))
        self.showAbsValue.setText(_translate("MainWindow", "Show absolute values"))
        self.showMagnitude.setText(_translate("MainWindow", "Magnitude"))
        self.label_vmax_2.setText(_translate("MainWindow", "in Hz"))
        self.rB_time_diff_meas.setText(_translate("MainWindow", "Time-difference"))
        self.rB_freq_diff_meas.setText(_translate("MainWindow", "Frequency-difference"))
        self.rB_abs_meas.setText(_translate("MainWindow", "Single Meas. (absolut)"))
        self.label_vmax_4.setText(_translate("MainWindow", "in Hz"))
        self.label_vmax_3.setText(_translate("MainWindow", "in Hz"))
        self.label_vmax_5.setText(_translate("MainWindow", "in Hz"))
        self.pB_set_ref_time_diff.setStatusTip(_translate("MainWindow", "Start measurement"))
        self.pB_set_ref_time_diff.setText(_translate("MainWindow", "Ref"))
        self.label_vmax_6.setText(_translate("MainWindow", "Reconstruction"))
        self.chB_diff.setText(_translate("MainWindow", "Difference"))
        self.chB_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.chB_plot_image_rec.setText(_translate("MainWindow", "Image"))
        self.chB_plot_graph.setText(_translate("MainWindow", "Graph"))
        self.pB_loadRef.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_loadRef.setText(_translate("MainWindow", "loadref"))
        self.chB_y_log.setText(_translate("MainWindow", "y log"))
        self.label_FEMRefinement.setText(_translate("MainWindow", "FEM Refinement"))
        self.label_replay_refresh_time.setText(_translate("MainWindow", "Refresh time [s]"))
        self.pB_gotoend_replay_meas.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_pause_replay_meas.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_play_replay_meas.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_backbegin_replay_meas.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.pB_stop_replay_meas.setStatusTip(_translate("MainWindow", "Plot the U-Shape diagramm"))
        self.lab_live_view.setText(_translate("MainWindow", "Live"))
        self.lab_actual_frame_cnt.setText(_translate("MainWindow", "Nb of acquired frames"))
        self.meas_dataset_name.setText(_translate("MainWindow", "DataSetName_default"))
        self.pB_stop_meas.setStatusTip(_translate("MainWindow", "Stop measurement"))
        self.pB_stop_meas.setText(_translate("MainWindow", "Stop"))
        self.pB_start_meas.setStatusTip(_translate("MainWindow", "Start measurement"))
        self.pB_start_meas.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Measurement"))
        self.label_vmax.setText(_translate("MainWindow", "vmax"))
        self.label_vmin.setText(_translate("MainWindow", "vmin"))
        self.normalize.setText(_translate("MainWindow", "Normalize"))
        self.cB_verbose.setText(_translate("MainWindow", "verbose"))
        self.label_vmax_9.setText(_translate("MainWindow", "n"))
        self.pB_set_eit.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_set_eit.setText(_translate("MainWindow", "set EIT"))
        self.label_vmax_7.setText(_translate("MainWindow", "p"))
        self.label_vmax_8.setText(_translate("MainWindow", "lamda"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "EIT Plotter"))
        self.cB_video_devices.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_refresh_video_devices.setToolTip(_translate("MainWindow", "test"))
        self.pB_refresh_video_devices.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_refresh_video_devices.setText(_translate("MainWindow", "Refresh"))
        self.pB_start_video.setText(_translate("MainWindow", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Video"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Graph"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_3), _translate("MainWindow", "Z"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_4), _translate("MainWindow", "Real"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_5), _translate("MainWindow", "Imag"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_9), _translate("MainWindow", "Magnitude"))
        self.tabWidget_Z.setTabText(self.tabWidget_Z.indexOf(self.tab_10), _translate("MainWindow", "Phase"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Values"))
        self.video_frame.setText(_translate("MainWindow", "Live Video"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "video"))
        self.video_frame_miniature.setText(_translate("MainWindow", "Live Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

