# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eit_app/app/gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/EIT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabW_settings = QtWidgets.QTabWidget(self.centralwidget)
        self.tabW_settings.setGeometry(QtCore.QRect(10, 10, 431, 1021))
        self.tabW_settings.setObjectName("tabW_settings")
        self.tab_device = QtWidgets.QWidget()
        self.tab_device.setObjectName("tab_device")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_device)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 50, 401, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lab_device_status = QtWidgets.QLabel(self.groupBox_3)
        self.lab_device_status.setGeometry(QtCore.QRect(10, 80, 381, 23))
        self.lab_device_status.setStatusTip("")
        self.lab_device_status.setAutoFillBackground(True)
        self.lab_device_status.setObjectName("lab_device_status")
        self.cB_ports = QtWidgets.QComboBox(self.groupBox_3)
        self.cB_ports.setGeometry(QtCore.QRect(10, 50, 381, 23))
        self.cB_ports.setToolTip("")
        self.cB_ports.setObjectName("cB_ports")
        self.pB_refresh = QtWidgets.QPushButton(self.groupBox_3)
        self.pB_refresh.setEnabled(True)
        self.pB_refresh.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.pB_refresh.setAutoFillBackground(False)
        self.pB_refresh.setObjectName("pB_refresh")
        self.pB_disconnect = QtWidgets.QPushButton(self.groupBox_3)
        self.pB_disconnect.setGeometry(QtCore.QRect(270, 20, 121, 23))
        self.pB_disconnect.setToolTip("")
        self.pB_disconnect.setAutoFillBackground(False)
        self.pB_disconnect.setObjectName("pB_disconnect")
        self.pB_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pB_connect.setGeometry(QtCore.QRect(140, 20, 121, 23))
        self.pB_connect.setAutoFillBackground(False)
        self.pB_connect.setObjectName("pB_connect")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_device)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 401, 540))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pB_save_setup = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_save_setup.setGeometry(QtCore.QRect(100, 490, 75, 23))
        self.pB_save_setup.setAutoFillBackground(False)
        self.pB_save_setup.setObjectName("pB_save_setup")
        self.pB_set_setup = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_set_setup.setEnabled(True)
        self.pB_set_setup.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.pB_set_setup.setAutoFillBackground(False)
        self.pB_set_setup.setObjectName("pB_set_setup")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 241, 411))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.LayoutParameters = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.LayoutParameters.setContentsMargins(0, 0, 0, 0)
        self.LayoutParameters.setHorizontalSpacing(6)
        self.LayoutParameters.setObjectName("LayoutParameters")
        self.label_Current_Amplitude = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Current_Amplitude.setObjectName("label_Current_Amplitude")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Current_Amplitude)
        self.sBd_exc_amp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_exc_amp.setDecimals(4)
        self.sBd_exc_amp.setMinimum(0.0001)
        self.sBd_exc_amp.setMaximum(10.0)
        self.sBd_exc_amp.setSingleStep(0.1)
        self.sBd_exc_amp.setObjectName("sBd_exc_amp")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBd_exc_amp)
        self.label_Burst = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst.setObjectName("label_Burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Burst)
        self.sB_burst = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_burst.setMaximum(255)
        self.sB_burst.setObjectName("sB_burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_burst)
        self.label_minF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_minF.setObjectName("label_minF")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_minF)
        self.sBd_freq_min = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_min.setMinimum(100.0)
        self.sBd_freq_min.setMaximum(1000000.0)
        self.sBd_freq_min.setObjectName("sBd_freq_min")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_min)
        self.label_maxF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxF.setObjectName("label_maxF")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_maxF)
        self.sBd_freq_max = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_max.setAutoFillBackground(False)
        self.sBd_freq_max.setMinimum(100.0)
        self.sBd_freq_max.setMaximum(1000000.0)
        self.sBd_freq_max.setObjectName("sBd_freq_max")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_max)
        self.label_Steps = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Steps.setObjectName("label_Steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Steps)
        self.sB_freq_steps = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_freq_steps.setMinimum(1)
        self.sB_freq_steps.setMaximum(255)
        self.sB_freq_steps.setObjectName("sB_freq_steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sB_freq_steps)
        self.label_Burst_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_Burst_5.setObjectName("label_Burst_5")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_Burst_5)
        self.cB_scale = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cB_scale.setEditable(False)
        self.cB_scale.setMaxVisibleItems(2)
        self.cB_scale.setObjectName("cB_scale")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cB_scale)
        self.label_FrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_FrameRate.setObjectName("label_FrameRate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_FrameRate)
        self.sBd_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_frame_rate.setDecimals(3)
        self.sBd_frame_rate.setMaximum(100.0)
        self.sBd_frame_rate.setSingleStep(0.001)
        self.sBd_frame_rate.setObjectName("sBd_frame_rate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sBd_frame_rate)
        self.label_maxFrameRate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_maxFrameRate.setObjectName("label_maxFrameRate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_maxFrameRate)
        self.sBd_max_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_max_frame_rate.setEnabled(False)
        self.sBd_max_frame_rate.setDecimals(3)
        self.sBd_max_frame_rate.setMaximum(100.0)
        self.sBd_max_frame_rate.setSingleStep(0.001)
        self.sBd_max_frame_rate.setObjectName("sBd_max_frame_rate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sBd_max_frame_rate)
        self.label_SN = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_SN.setObjectName("label_SN")
        self.LayoutParameters.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_SN)
        self.lE_sn = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_sn.setEnabled(False)
        self.lE_sn.setToolTip("")
        self.lE_sn.setWhatsThis("")
        self.lE_sn.setInputMask("")
        self.lE_sn.setFrame(True)
        self.lE_sn.setObjectName("lE_sn")
        self.LayoutParameters.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lE_sn)
        self.label_IP = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IP.setObjectName("label_IP")
        self.LayoutParameters.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_IP)
        self.lE_ip = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_ip.setToolTip("")
        self.lE_ip.setWhatsThis("")
        self.lE_ip.setInputMask("")
        self.lE_ip.setFrame(True)
        self.lE_ip.setObjectName("lE_ip")
        self.LayoutParameters.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lE_ip)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.LayoutParameters.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lE_mac = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_mac.setEnabled(False)
        self.lE_mac.setObjectName("lE_mac")
        self.LayoutParameters.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lE_mac)
        self.label_OutputConfig = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_OutputConfig.setObjectName("label_OutputConfig")
        self.LayoutParameters.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_OutputConfig)
        self.chB_dhcp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_dhcp.setEnabled(False)
        self.chB_dhcp.setChecked(False)
        self.chB_dhcp.setObjectName("chB_dhcp")
        self.LayoutParameters.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.chB_dhcp)
        self.chB_exc_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_exc_stamp.setEnabled(False)
        self.chB_exc_stamp.setChecked(True)
        self.chB_exc_stamp.setObjectName("chB_exc_stamp")
        self.LayoutParameters.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.chB_exc_stamp)
        self.chB_current_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_current_stamp.setEnabled(False)
        self.chB_current_stamp.setChecked(True)
        self.chB_current_stamp.setObjectName("chB_current_stamp")
        self.LayoutParameters.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.chB_current_stamp)
        self.chB_time_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_time_stamp.setEnabled(False)
        self.chB_time_stamp.setChecked(True)
        self.chB_time_stamp.setObjectName("chB_time_stamp")
        self.LayoutParameters.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.chB_time_stamp)
        self.pB_load_setup = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_load_setup.setGeometry(QtCore.QRect(10, 490, 75, 23))
        self.pB_load_setup.setAutoFillBackground(False)
        self.pB_load_setup.setObjectName("pB_load_setup")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 60, 134, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayoutExcitationPattern = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayoutExcitationPattern.setContentsMargins(0, 0, 0, 0)
        self.vLayoutExcitationPattern.setObjectName("vLayoutExcitationPattern")
        self.label_ExcitationPattern = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ExcitationPattern.setObjectName("label_ExcitationPattern")
        self.vLayoutExcitationPattern.addWidget(self.label_ExcitationPattern)
        self.tw_exc_pattern = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tw_exc_pattern.setObjectName("tw_exc_pattern")
        self.tw_exc_pattern.setColumnCount(2)
        self.tw_exc_pattern.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_pattern.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_pattern.setHorizontalHeaderItem(1, item)
        self.tw_exc_pattern.horizontalHeader().setDefaultSectionSize(40)
        self.vLayoutExcitationPattern.addWidget(self.tw_exc_pattern)
        self.pB_get_setup = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_get_setup.setGeometry(QtCore.QRect(140, 20, 121, 23))
        self.pB_get_setup.setAutoFillBackground(False)
        self.pB_get_setup.setObjectName("pB_get_setup")
        self.pB_reset = QtWidgets.QPushButton(self.groupBox_4)
        self.pB_reset.setGeometry(QtCore.QRect(270, 20, 121, 23))
        self.pB_reset.setAutoFillBackground(False)
        self.pB_reset.setObjectName("pB_reset")
        self.textEditlog = QtWidgets.QTextEdit(self.tab_device)
        self.textEditlog.setGeometry(QtCore.QRect(20, 730, 301, 141))
        self.textEditlog.setObjectName("textEditlog")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_device)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 391, 27))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.chB_plot_graph_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.chB_plot_graph_2.setChecked(True)
        self.chB_plot_graph_2.setObjectName("chB_plot_graph_2")
        self.gridLayout_4.addWidget(self.chB_plot_graph_2, 0, 0, 1, 1)
        self.chB_diff_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.chB_diff_2.setChecked(False)
        self.chB_diff_2.setObjectName("chB_diff_2")
        self.gridLayout_4.addWidget(self.chB_diff_2, 0, 2, 1, 1)
        self.chB_Uplot_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.chB_Uplot_2.setChecked(False)
        self.chB_Uplot_2.setObjectName("chB_Uplot_2")
        self.gridLayout_4.addWidget(self.chB_Uplot_2, 0, 1, 1, 1)
        self.tabW_settings.addTab(self.tab_device, "")
        self.tab_measurements = QtWidgets.QWidget()
        self.tab_measurements.setObjectName("tab_measurements")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 410, 401, 270))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cB_current_idx_frame = QtWidgets.QComboBox(self.groupBox_2)
        self.cB_current_idx_frame.setGeometry(QtCore.QRect(120, 20, 69, 23))
        self.cB_current_idx_frame.setObjectName("cB_current_idx_frame")
        self.lab_current_frame_indx = QtWidgets.QLabel(self.groupBox_2)
        self.lab_current_frame_indx.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.lab_current_frame_indx.setObjectName("lab_current_frame_indx")
        self.tE_frame_info = QtWidgets.QTextEdit(self.groupBox_2)
        self.tE_frame_info.setGeometry(QtCore.QRect(10, 50, 381, 211))
        self.tE_frame_info.setObjectName("tE_frame_info")
        self.groupBox = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 401, 161))
        self.groupBox.setObjectName("groupBox")
        self.meas_progress_bar = QtWidgets.QProgressBar(self.groupBox)
        self.meas_progress_bar.setGeometry(QtCore.QRect(220, 120, 171, 23))
        self.meas_progress_bar.setProperty("value", 0)
        self.meas_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.meas_progress_bar.setObjectName("meas_progress_bar")
        self.lab_actual_frame_cnt = QtWidgets.QLabel(self.groupBox)
        self.lab_actual_frame_cnt.setGeometry(QtCore.QRect(10, 120, 141, 23))
        self.lab_actual_frame_cnt.setObjectName("lab_actual_frame_cnt")
        self.sB_actual_frame_cnt = QtWidgets.QSpinBox(self.groupBox)
        self.sB_actual_frame_cnt.setEnabled(True)
        self.sB_actual_frame_cnt.setGeometry(QtCore.QRect(160, 120, 51, 23))
        self.sB_actual_frame_cnt.setFrame(True)
        self.sB_actual_frame_cnt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sB_actual_frame_cnt.setMaximum(999)
        self.sB_actual_frame_cnt.setObjectName("sB_actual_frame_cnt")
        self.lab_live_meas_status = QtWidgets.QLabel(self.groupBox)
        self.lab_live_meas_status.setGeometry(QtCore.QRect(270, 20, 121, 23))
        self.lab_live_meas_status.setAutoFillBackground(True)
        self.lab_live_meas_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_live_meas_status.setObjectName("lab_live_meas_status")
        self.lE_meas_dataset_dir = QtWidgets.QLineEdit(self.groupBox)
        self.lE_meas_dataset_dir.setGeometry(QtCore.QRect(10, 50, 380, 23))
        self.lE_meas_dataset_dir.setObjectName("lE_meas_dataset_dir")
        self.pB_stop_meas = QtWidgets.QPushButton(self.groupBox)
        self.pB_stop_meas.setGeometry(QtCore.QRect(140, 20, 121, 23))
        self.pB_stop_meas.setAutoFillBackground(False)
        self.pB_stop_meas.setObjectName("pB_stop_meas")
        self.pB_start_meas = QtWidgets.QPushButton(self.groupBox)
        self.pB_start_meas.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.pB_start_meas.setAutoFillBackground(False)
        self.pB_start_meas.setObjectName("pB_start_meas")
        self.chB_dataset_autosave = QtWidgets.QCheckBox(self.groupBox)
        self.chB_dataset_autosave.setGeometry(QtCore.QRect(10, 80, 71, 23))
        self.chB_dataset_autosave.setChecked(True)
        self.chB_dataset_autosave.setObjectName("chB_dataset_autosave")
        self.chB_dataset_save_img = QtWidgets.QCheckBox(self.groupBox)
        self.chB_dataset_save_img.setGeometry(QtCore.QRect(90, 80, 71, 23))
        self.chB_dataset_save_img.setChecked(True)
        self.chB_dataset_save_img.setObjectName("chB_dataset_save_img")
        self.chB_load_after_meas = QtWidgets.QCheckBox(self.groupBox)
        self.chB_load_after_meas.setGeometry(QtCore.QRect(160, 80, 101, 23))
        self.chB_load_after_meas.setChecked(True)
        self.chB_load_after_meas.setObjectName("chB_load_after_meas")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 180, 401, 221))
        self.groupBox_6.setObjectName("groupBox_6")
        self.slider_replay = QtWidgets.QSlider(self.groupBox_6)
        self.slider_replay.setGeometry(QtCore.QRect(10, 160, 381, 23))
        self.slider_replay.setOrientation(QtCore.Qt.Horizontal)
        self.slider_replay.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_replay.setTickInterval(0)
        self.slider_replay.setObjectName("slider_replay")
        self.pB_replay_goto_end = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_replay_goto_end.setGeometry(QtCore.QRect(79, 121, 28, 24))
        self.pB_replay_goto_end.setAutoFillBackground(False)
        self.pB_replay_goto_end.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icon_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_goto_end.setIcon(icon1)
        self.pB_replay_goto_end.setAutoDefault(False)
        self.pB_replay_goto_end.setFlat(False)
        self.pB_replay_goto_end.setObjectName("pB_replay_goto_end")
        self.pB_replay_play = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_replay_play.setGeometry(QtCore.QRect(45, 121, 28, 24))
        self.pB_replay_play.setAutoFillBackground(False)
        self.pB_replay_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icon_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_play.setIcon(icon2)
        self.pB_replay_play.setCheckable(False)
        self.pB_replay_play.setAutoDefault(False)
        self.pB_replay_play.setFlat(False)
        self.pB_replay_play.setObjectName("pB_replay_play")
        self.pB_replay_back_begin = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_replay_back_begin.setGeometry(QtCore.QRect(11, 121, 28, 24))
        self.pB_replay_back_begin.setAutoFillBackground(False)
        self.pB_replay_back_begin.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icon_begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_back_begin.setIcon(icon3)
        self.pB_replay_back_begin.setCheckable(False)
        self.pB_replay_back_begin.setChecked(False)
        self.pB_replay_back_begin.setAutoDefault(False)
        self.pB_replay_back_begin.setFlat(False)
        self.pB_replay_back_begin.setObjectName("pB_replay_back_begin")
        self.sB_replay_time = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.sB_replay_time.setGeometry(QtCore.QRect(339, 120, 51, 23))
        self.sB_replay_time.setDecimals(1)
        self.sB_replay_time.setMinimum(0.1)
        self.sB_replay_time.setMaximum(10.0)
        self.sB_replay_time.setSingleStep(0.1)
        self.sB_replay_time.setProperty("value", 1.0)
        self.sB_replay_time.setObjectName("sB_replay_time")
        self.lab_replay_time = QtWidgets.QLabel(self.groupBox_6)
        self.lab_replay_time.setGeometry(QtCore.QRect(250, 120, 91, 23))
        self.lab_replay_time.setObjectName("lab_replay_time")
        self.pB_load_meas_dataset = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_load_meas_dataset.setGeometry(QtCore.QRect(10, 20, 181, 23))
        self.pB_load_meas_dataset.setAutoFillBackground(False)
        self.pB_load_meas_dataset.setObjectName("pB_load_meas_dataset")
        self.lab_replay_status = QtWidgets.QLabel(self.groupBox_6)
        self.lab_replay_status.setGeometry(QtCore.QRect(210, 20, 181, 23))
        self.lab_replay_status.setAutoFillBackground(True)
        self.lab_replay_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_replay_status.setObjectName("lab_replay_status")
        self.tE_load_dataset_dir = QtWidgets.QTextEdit(self.groupBox_6)
        self.tE_load_dataset_dir.setEnabled(True)
        self.tE_load_dataset_dir.setGeometry(QtCore.QRect(10, 50, 381, 50))
        self.tE_load_dataset_dir.setObjectName("tE_load_dataset_dir")
        self.pB_export_meas_csv = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_export_meas_csv.setGeometry(QtCore.QRect(10, 190, 181, 23))
        self.pB_export_meas_csv.setAutoFillBackground(False)
        self.pB_export_meas_csv.setObjectName("pB_export_meas_csv")
        self.pB_load_ref_dataset = QtWidgets.QPushButton(self.groupBox_6)
        self.pB_load_ref_dataset.setGeometry(QtCore.QRect(200, 190, 181, 23))
        self.pB_load_ref_dataset.setAutoFillBackground(False)
        self.pB_load_ref_dataset.setObjectName("pB_load_ref_dataset")
        self.pB_load_eidors_fwd_solution = QtWidgets.QPushButton(self.tab_measurements)
        self.pB_load_eidors_fwd_solution.setGeometry(QtCore.QRect(20, 680, 181, 23))
        self.pB_load_eidors_fwd_solution.setAutoFillBackground(False)
        self.pB_load_eidors_fwd_solution.setObjectName("pB_load_eidors_fwd_solution")
        self.sB_eidors_factor = QtWidgets.QDoubleSpinBox(self.tab_measurements)
        self.sB_eidors_factor.setGeometry(QtCore.QRect(270, 680, 91, 23))
        self.sB_eidors_factor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sB_eidors_factor.setSuffix("")
        self.sB_eidors_factor.setDecimals(3)
        self.sB_eidors_factor.setMinimum(-1000000.0)
        self.sB_eidors_factor.setMaximum(1000000.0)
        self.sB_eidors_factor.setSingleStep(0.1)
        self.sB_eidors_factor.setProperty("value", 1.0)
        self.sB_eidors_factor.setObjectName("sB_eidors_factor")
        self.pB_export_data_meas_vs_eidors = QtWidgets.QPushButton(self.tab_measurements)
        self.pB_export_data_meas_vs_eidors.setGeometry(QtCore.QRect(20, 710, 231, 23))
        self.pB_export_data_meas_vs_eidors.setAutoFillBackground(False)
        self.pB_export_data_meas_vs_eidors.setObjectName("pB_export_data_meas_vs_eidors")
        self.tabW_settings.addTab(self.tab_measurements, "")
        self.tab_eit_model = QtWidgets.QWidget()
        self.tab_eit_model.setObjectName("tab_eit_model")
        self.tabW_reconstruction = QtWidgets.QTabWidget(self.tab_eit_model)
        self.tabW_reconstruction.setGeometry(QtCore.QRect(10, 290, 411, 271))
        self.tabW_reconstruction.setObjectName("tabW_reconstruction")
        self.tab_pyeit = QtWidgets.QWidget()
        self.tab_pyeit.setObjectName("tab_pyeit")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_pyeit)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 70, 238, 175))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_vmax_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_7.setObjectName("label_vmax_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_vmax_7)
        self.eit_p = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.eit_p.setDecimals(1)
        self.eit_p.setMinimum(-1000000000000000.0)
        self.eit_p.setMaximum(1000000000000000.0)
        self.eit_p.setProperty("value", 0.5)
        self.eit_p.setObjectName("eit_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eit_p)
        self.label_vmax_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_8.setObjectName("label_vmax_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_vmax_8)
        self.eit_lamda = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.eit_lamda.setDecimals(4)
        self.eit_lamda.setMinimum(-1000000000000000.0)
        self.eit_lamda.setMaximum(1000000000000000.0)
        self.eit_lamda.setProperty("value", 0.01)
        self.eit_lamda.setObjectName("eit_lamda")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eit_lamda)
        self.label_vmax_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_9.setObjectName("label_vmax_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_vmax_9)
        self.eit_n = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.eit_n.setDecimals(0)
        self.eit_n.setMinimum(-1000000000000000.0)
        self.eit_n.setMaximum(1000000000000000.0)
        self.eit_n.setProperty("value", 64.0)
        self.eit_n.setObjectName("eit_n")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eit_n)
        self.eit_FEMRefinement = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.eit_FEMRefinement.setDecimals(4)
        self.eit_FEMRefinement.setMinimum(0.0)
        self.eit_FEMRefinement.setMaximum(10.0)
        self.eit_FEMRefinement.setSingleStep(0.001)
        self.eit_FEMRefinement.setProperty("value", 0.1)
        self.eit_FEMRefinement.setObjectName("eit_FEMRefinement")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.eit_FEMRefinement)
        self.label_FEMRefinement = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_FEMRefinement.setObjectName("label_FEMRefinement")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_FEMRefinement)
        self.label_FEMRefinement_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_FEMRefinement_2.setObjectName("label_FEMRefinement_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_FEMRefinement_2)
        self.dSB_pyeit_bckgrnd = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.dSB_pyeit_bckgrnd.setDecimals(4)
        self.dSB_pyeit_bckgrnd.setMinimum(0.0)
        self.dSB_pyeit_bckgrnd.setMaximum(10.0)
        self.dSB_pyeit_bckgrnd.setSingleStep(0.001)
        self.dSB_pyeit_bckgrnd.setProperty("value", 0.1)
        self.dSB_pyeit_bckgrnd.setObjectName("dSB_pyeit_bckgrnd")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dSB_pyeit_bckgrnd)
        self.cB_solver = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.cB_solver.setObjectName("cB_solver")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cB_solver)
        self.lab_solver = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lab_solver.setObjectName("lab_solver")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lab_solver)
        self.normalize = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.normalize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.normalize.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.normalize.setObjectName("normalize")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.normalize)
        self.tabW_reconstruction.addTab(self.tab_pyeit, "")
        self.tab_nn = QtWidgets.QWidget()
        self.tab_nn.setObjectName("tab_nn")
        self.lE_load_model_dir = QtWidgets.QLineEdit(self.tab_nn)
        self.lE_load_model_dir.setEnabled(False)
        self.lE_load_model_dir.setGeometry(QtCore.QRect(10, 20, 390, 23))
        self.lE_load_model_dir.setObjectName("lE_load_model_dir")
        self.tabW_reconstruction.addTab(self.tab_nn, "")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_eit_model)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 411, 261))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 387, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.cB_eit_imaging_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_eit_imaging_type.setCurrentText("")
        self.cB_eit_imaging_type.setObjectName("cB_eit_imaging_type")
        self.gridLayout.addWidget(self.cB_eit_imaging_type, 0, 0, 1, 5)
        self.cB_freq_meas_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_freq_meas_1.sizePolicy().hasHeightForWidth())
        self.cB_freq_meas_1.setSizePolicy(sizePolicy)
        self.cB_freq_meas_1.setMinimumSize(QtCore.QSize(78, 0))
        self.cB_freq_meas_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cB_freq_meas_1.setObjectName("cB_freq_meas_1")
        self.gridLayout.addWidget(self.cB_freq_meas_1, 2, 2, 1, 2)
        self.lab_ref_frame_idx = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_ref_frame_idx.sizePolicy().hasHeightForWidth())
        self.lab_ref_frame_idx.setSizePolicy(sizePolicy)
        self.lab_ref_frame_idx.setObjectName("lab_ref_frame_idx")
        self.gridLayout.addWidget(self.lab_ref_frame_idx, 1, 4, 1, 1)
        self.cB_ref_frame_idx = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_ref_frame_idx.sizePolicy().hasHeightForWidth())
        self.cB_ref_frame_idx.setSizePolicy(sizePolicy)
        self.cB_ref_frame_idx.setMinimumSize(QtCore.QSize(78, 0))
        self.cB_ref_frame_idx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cB_ref_frame_idx.setObjectName("cB_ref_frame_idx")
        self.gridLayout.addWidget(self.cB_ref_frame_idx, 2, 4, 1, 1)
        self.lab_freq_meas_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_freq_meas_0.setObjectName("lab_freq_meas_0")
        self.gridLayout.addWidget(self.lab_freq_meas_0, 1, 0, 1, 2)
        self.lab_freq_meas_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_freq_meas_1.sizePolicy().hasHeightForWidth())
        self.lab_freq_meas_1.setSizePolicy(sizePolicy)
        self.lab_freq_meas_1.setObjectName("lab_freq_meas_1")
        self.gridLayout.addWidget(self.lab_freq_meas_1, 1, 2, 1, 2)
        self.cB_freq_meas_0 = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_freq_meas_0.sizePolicy().hasHeightForWidth())
        self.cB_freq_meas_0.setSizePolicy(sizePolicy)
        self.cB_freq_meas_0.setCurrentText("")
        self.cB_freq_meas_0.setObjectName("cB_freq_meas_0")
        self.gridLayout.addWidget(self.cB_freq_meas_0, 2, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 260, 60))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showAbsValue = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.showAbsValue.setObjectName("showAbsValue")
        self.gridLayout_2.addWidget(self.showAbsValue, 1, 0, 1, 1)
        self.cB_transform_volt = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cB_transform_volt.setCurrentText("")
        self.cB_transform_volt.setObjectName("cB_transform_volt")
        self.gridLayout_2.addWidget(self.cB_transform_volt, 0, 0, 1, 1)
        self.scalePlot_vmax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.scalePlot_vmax.setGeometry(QtCore.QRect(100, 200, 90, 20))
        self.scalePlot_vmax.setDecimals(4)
        self.scalePlot_vmax.setMinimum(-1000000000000000.0)
        self.scalePlot_vmax.setMaximum(1000000000000000.0)
        self.scalePlot_vmax.setObjectName("scalePlot_vmax")
        self.label_vmax = QtWidgets.QLabel(self.groupBox_5)
        self.label_vmax.setGeometry(QtCore.QRect(20, 200, 71, 20))
        self.label_vmax.setObjectName("label_vmax")
        self.scalePlot_vmin = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.scalePlot_vmin.setGeometry(QtCore.QRect(100, 230, 90, 20))
        self.scalePlot_vmin.setDecimals(4)
        self.scalePlot_vmin.setMinimum(-1000000000000000.0)
        self.scalePlot_vmin.setMaximum(1000000000000000.0)
        self.scalePlot_vmin.setObjectName("scalePlot_vmin")
        self.label_vmin = QtWidgets.QLabel(self.groupBox_5)
        self.label_vmin.setGeometry(QtCore.QRect(20, 230, 71, 20))
        self.label_vmin.setObjectName("label_vmin")
        self.pB_set_reconstruction = QtWidgets.QPushButton(self.tab_eit_model)
        self.pB_set_reconstruction.setGeometry(QtCore.QRect(290, 280, 131, 23))
        self.pB_set_reconstruction.setAutoFillBackground(False)
        self.pB_set_reconstruction.setObjectName("pB_set_reconstruction")
        self.lab_log_level = QtWidgets.QLabel(self.tab_eit_model)
        self.lab_log_level.setGeometry(QtCore.QRect(20, 640, 64, 20))
        self.lab_log_level.setObjectName("lab_log_level")
        self.cB_log_level = QtWidgets.QComboBox(self.tab_eit_model)
        self.cB_log_level.setGeometry(QtCore.QRect(90, 640, 130, 23))
        self.cB_log_level.setToolTip("")
        self.cB_log_level.setObjectName("cB_log_level")
        self.cB_eit_mdl_ctlg = QtWidgets.QComboBox(self.tab_eit_model)
        self.cB_eit_mdl_ctlg.setGeometry(QtCore.QRect(90, 720, 321, 20))
        self.cB_eit_mdl_ctlg.setCurrentText("")
        self.cB_eit_mdl_ctlg.setObjectName("cB_eit_mdl_ctlg")
        self.lab_eit_mdl_ctlg = QtWidgets.QLabel(self.tab_eit_model)
        self.lab_eit_mdl_ctlg.setGeometry(QtCore.QRect(30, 720, 64, 20))
        self.lab_eit_mdl_ctlg.setObjectName("lab_eit_mdl_ctlg")
        self.pB_refresh_eit_mdl_ctlg = QtWidgets.QPushButton(self.tab_eit_model)
        self.pB_refresh_eit_mdl_ctlg.setGeometry(QtCore.QRect(280, 750, 131, 23))
        self.pB_refresh_eit_mdl_ctlg.setAutoFillBackground(False)
        self.pB_refresh_eit_mdl_ctlg.setObjectName("pB_refresh_eit_mdl_ctlg")
        self.tabW_settings.addTab(self.tab_eit_model, "")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.cB_video_devices = QtWidgets.QComboBox(self.tab_video)
        self.cB_video_devices.setGeometry(QtCore.QRect(90, 30, 81, 22))
        self.cB_video_devices.setToolTip("")
        self.cB_video_devices.setEditable(False)
        self.cB_video_devices.setObjectName("cB_video_devices")
        self.pB_refresh_video_devices = QtWidgets.QPushButton(self.tab_video)
        self.pB_refresh_video_devices.setEnabled(True)
        self.pB_refresh_video_devices.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.pB_refresh_video_devices.setAutoFillBackground(False)
        self.pB_refresh_video_devices.setObjectName("pB_refresh_video_devices")
        self.cB_img_file_ext = QtWidgets.QComboBox(self.tab_video)
        self.cB_img_file_ext.setGeometry(QtCore.QRect(260, 180, 73, 20))
        self.cB_img_file_ext.setCurrentText("")
        self.cB_img_file_ext.setObjectName("cB_img_file_ext")
        self.cB_img_size = QtWidgets.QComboBox(self.tab_video)
        self.cB_img_size.setGeometry(QtCore.QRect(132, 180, 111, 20))
        self.cB_img_size.setCurrentText("")
        self.cB_img_size.setObjectName("cB_img_size")
        self.pB_capture_start = QtWidgets.QPushButton(self.tab_video)
        self.pB_capture_start.setEnabled(True)
        self.pB_capture_start.setGeometry(QtCore.QRect(190, 110, 75, 23))
        self.pB_capture_start.setAutoFillBackground(False)
        self.pB_capture_start.setObjectName("pB_capture_start")
        self.pB_capture_stop = QtWidgets.QPushButton(self.tab_video)
        self.pB_capture_stop.setEnabled(True)
        self.pB_capture_stop.setGeometry(QtCore.QRect(270, 110, 75, 23))
        self.pB_capture_stop.setAutoFillBackground(False)
        self.pB_capture_stop.setObjectName("pB_capture_stop")
        self.pB_capture_snapshot = QtWidgets.QPushButton(self.tab_video)
        self.pB_capture_snapshot.setEnabled(True)
        self.pB_capture_snapshot.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.pB_capture_snapshot.setAutoFillBackground(False)
        self.pB_capture_snapshot.setObjectName("pB_capture_snapshot")
        self.tabW_settings.addTab(self.tab_video, "")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(1240, 20, 660, 511))
        self.groupBox_7.setObjectName("groupBox_7")
        self.video_frame = QtWidgets.QLabel(self.groupBox_7)
        self.video_frame.setGeometry(QtCore.QRect(10, 20, 640, 480))
        self.video_frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_frame.setMouseTracking(True)
        self.video_frame.setAutoFillBackground(False)
        self.video_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame.setObjectName("video_frame")
        self.video_frame_miniature = QtWidgets.QLabel(self.centralwidget)
        self.video_frame_miniature.setGeometry(QtCore.QRect(740, 60, 201, 100))
        self.video_frame_miniature.setMouseTracking(False)
        self.video_frame_miniature.setAutoFillBackground(False)
        self.video_frame_miniature.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame_miniature.setObjectName("video_frame_miniature")
        self.pB_somahey = QtWidgets.QPushButton(self.centralwidget)
        self.pB_somahey.setGeometry(QtCore.QRect(820, 130, 75, 23))
        self.pB_somahey.setObjectName("pB_somahey")
        self.groupBox_21 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_21.setGeometry(QtCore.QRect(450, 10, 781, 510))
        self.groupBox_21.setObjectName("groupBox_21")
        self.chB_plot_image_rec = QtWidgets.QCheckBox(self.groupBox_21)
        self.chB_plot_image_rec.setGeometry(QtCore.QRect(10, 20, 50, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chB_plot_image_rec.sizePolicy().hasHeightForWidth())
        self.chB_plot_image_rec.setSizePolicy(sizePolicy)
        self.chB_plot_image_rec.setObjectName("chB_plot_image_rec")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_21)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 10, 680, 491))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_rec = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_rec.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_rec.setContentsMargins(0, 0, 0, 0)
        self.layout_rec.setObjectName("layout_rec")
        self.tabW_rec = QtWidgets.QTabWidget(self.centralwidget)
        self.tabW_rec.setGeometry(QtCore.QRect(450, 530, 1471, 501))
        self.tabW_rec.setTabBarAutoHide(True)
        self.tabW_rec.setObjectName("tabW_rec")
        self.tab_meas_voltages = QtWidgets.QWidget()
        self.tab_meas_voltages.setObjectName("tab_meas_voltages")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_meas_voltages)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 10, 1450, 460))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_8)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 10, 1350, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_graphs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_graphs.setContentsMargins(0, 0, 0, 0)
        self.layout_graphs.setObjectName("layout_graphs")
        self.chB_y_log = QtWidgets.QCheckBox(self.groupBox_8)
        self.chB_y_log.setGeometry(QtCore.QRect(10, 130, 48, 17))
        self.chB_y_log.setObjectName("chB_y_log")
        self.chB_plot_graph = QtWidgets.QCheckBox(self.groupBox_8)
        self.chB_plot_graph.setGeometry(QtCore.QRect(10, 50, 48, 17))
        self.chB_plot_graph.setChecked(True)
        self.chB_plot_graph.setObjectName("chB_plot_graph")
        self.chB_diff = QtWidgets.QCheckBox(self.groupBox_8)
        self.chB_diff.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.chB_diff.setChecked(True)
        self.chB_diff.setObjectName("chB_diff")
        self.chB_Uplot = QtWidgets.QCheckBox(self.groupBox_8)
        self.chB_Uplot.setGeometry(QtCore.QRect(10, 80, 190, 17))
        self.chB_Uplot.setChecked(True)
        self.chB_Uplot.setObjectName("chB_Uplot")
        self.tabW_rec.addTab(self.tab_meas_voltages, "")
        self.tab_values = QtWidgets.QWidget()
        self.tab_values.setObjectName("tab_values")
        self.tabW_values = QtWidgets.QTabWidget(self.tab_values)
        self.tabW_values.setGeometry(QtCore.QRect(10, 10, 661, 461))
        self.tabW_values.setObjectName("tabW_values")
        self.tab_Z = QtWidgets.QWidget()
        self.tab_Z.setObjectName("tab_Z")
        self.tableWidgetvoltages_Z = QtWidgets.QTableWidget(self.tab_Z)
        self.tableWidgetvoltages_Z.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z.setObjectName("tableWidgetvoltages_Z")
        self.tableWidgetvoltages_Z.setColumnCount(2)
        self.tableWidgetvoltages_Z.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_Z, "")
        self.tab_real = QtWidgets.QWidget()
        self.tab_real.setObjectName("tab_real")
        self.tableWidgetvoltages_Z_real = QtWidgets.QTableWidget(self.tab_real)
        self.tableWidgetvoltages_Z_real.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z_real.setObjectName("tableWidgetvoltages_Z_real")
        self.tableWidgetvoltages_Z_real.setColumnCount(2)
        self.tableWidgetvoltages_Z_real.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_real, "")
        self.tab_imag = QtWidgets.QWidget()
        self.tab_imag.setObjectName("tab_imag")
        self.tableWidgetvoltages_Z_imag = QtWidgets.QTableWidget(self.tab_imag)
        self.tableWidgetvoltages_Z_imag.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z_imag.setObjectName("tableWidgetvoltages_Z_imag")
        self.tableWidgetvoltages_Z_imag.setColumnCount(2)
        self.tableWidgetvoltages_Z_imag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_imag, "")
        self.tab_phase = QtWidgets.QWidget()
        self.tab_phase.setObjectName("tab_phase")
        self.tabW_values.addTab(self.tab_phase, "")
        self.tab_magnitude = QtWidgets.QWidget()
        self.tab_magnitude.setObjectName("tab_magnitude")
        self.tabW_values.addTab(self.tab_magnitude, "")
        self.tabW_rec.addTab(self.tab_values, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 20, 1350, 441))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_ch_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_ch_graph.setContentsMargins(0, 0, 0, 0)
        self.layout_ch_graph.setObjectName("layout_ch_graph")
        self.tabW_rec.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabW_settings.setCurrentIndex(2)
        self.tabW_reconstruction.setCurrentIndex(0)
        self.tabW_rec.setCurrentIndex(2)
        self.tabW_values.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "EIT device"))
        self.lab_device_status.setText(_translate("MainWindow", "Not Connected"))
        self.cB_ports.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_refresh.setToolTip(_translate("MainWindow", "test"))
        self.pB_refresh.setStatusTip(_translate("MainWindow", "Refresh the available serial port list (Ctrl + R)"))
        self.pB_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pB_refresh.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pB_disconnect.setStatusTip(_translate("MainWindow", "Disconnect the serial port (Shift + D)"))
        self.pB_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pB_disconnect.setShortcut(_translate("MainWindow", "Shift+D"))
        self.pB_connect.setStatusTip(_translate("MainWindow", "Connect to the selected serial port (Shift +C)"))
        self.pB_connect.setText(_translate("MainWindow", "Connect"))
        self.pB_connect.setShortcut(_translate("MainWindow", "Shift+C"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Setup of device"))
        self.pB_save_setup.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_save_setup.setText(_translate("MainWindow", "Save_Setup"))
        self.pB_set_setup.setStatusTip(_translate("MainWindow", "Send measurements parameters to connected device (Shift +S)"))
        self.pB_set_setup.setText(_translate("MainWindow", "Set_Setup"))
        self.pB_set_setup.setShortcut(_translate("MainWindow", "Shift+S"))
        self.label_Current_Amplitude.setText(_translate("MainWindow", "Current Amplitude [mA]"))
        self.label_Burst.setText(_translate("MainWindow", "Burst number"))
        self.label_minF.setText(_translate("MainWindow", "Min Frequency [Hz]"))
        self.label_maxF.setText(_translate("MainWindow", "Max Frequency [Hz]"))
        self.label_Steps.setText(_translate("MainWindow", "Steps number"))
        self.label_Burst_5.setText(_translate("MainWindow", "Scale"))
        self.label_FrameRate.setText(_translate("MainWindow", "Frame rate [fps]"))
        self.label_maxFrameRate.setText(_translate("MainWindow", "Max Frame rate [fps]"))
        self.label_SN.setText(_translate("MainWindow", "S/N"))
        self.label_IP.setText(_translate("MainWindow", "IP Adress"))
        self.label_3.setText(_translate("MainWindow", "MAC Adress"))
        self.label_OutputConfig.setText(_translate("MainWindow", "Output config"))
        self.chB_dhcp.setText(_translate("MainWindow", "DHCP_Activated"))
        self.chB_exc_stamp.setText(_translate("MainWindow", "Excitation_Stamp"))
        self.chB_current_stamp.setText(_translate("MainWindow", "Current_Stamp"))
        self.chB_time_stamp.setText(_translate("MainWindow", "Time_Stamp"))
        self.pB_load_setup.setStatusTip(_translate("MainWindow", "Load parameters from file (*.xlsx)"))
        self.pB_load_setup.setText(_translate("MainWindow", "Load_Setup"))
        self.label_ExcitationPattern.setText(_translate("MainWindow", "Excitation pattern"))
        item = self.tw_exc_pattern.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Inj+ "))
        item = self.tw_exc_pattern.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inj-"))
        self.pB_get_setup.setStatusTip(_translate("MainWindow", "Ask measurements parameters from connected device (Shift +G)"))
        self.pB_get_setup.setText(_translate("MainWindow", "Get_Setup"))
        self.pB_get_setup.setShortcut(_translate("MainWindow", "Shift+G"))
        self.pB_reset.setStatusTip(_translate("MainWindow", "Software reset of the device (reconnection needed after 10-15 sec) (Ctrl + Shift +C)"))
        self.pB_reset.setText(_translate("MainWindow", "Reset"))
        self.pB_reset.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.chB_plot_graph_2.setText(_translate("MainWindow", "USB FS"))
        self.chB_diff_2.setText(_translate("MainWindow", "Ethernet"))
        self.chB_Uplot_2.setText(_translate("MainWindow", "USB HS"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_device), _translate("MainWindow", "Device"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Frame infos"))
        self.lab_current_frame_indx.setText(_translate("MainWindow", "Current frame #"))
        self.groupBox.setTitle(_translate("MainWindow", "Acquisition"))
        self.lab_actual_frame_cnt.setText(_translate("MainWindow", "Acquisition progress of frame"))
        self.sB_actual_frame_cnt.setPrefix(_translate("MainWindow", "#"))
        self.lab_live_meas_status.setText(_translate("MainWindow", "Meas status"))
        self.lE_meas_dataset_dir.setText(_translate("MainWindow", "default_autosave_dir"))
        self.pB_stop_meas.setStatusTip(_translate("MainWindow", "Stop measurement (Esc)"))
        self.pB_stop_meas.setText(_translate("MainWindow", "Stop"))
        self.pB_stop_meas.setShortcut(_translate("MainWindow", "Esc"))
        self.pB_start_meas.setStatusTip(_translate("MainWindow", "Start measurement (Ctrl + Shift +Space)"))
        self.pB_start_meas.setText(_translate("MainWindow", "Start"))
        self.pB_start_meas.setShortcut(_translate("MainWindow", "Ctrl+Shift+Space"))
        self.chB_dataset_autosave.setText(_translate("MainWindow", "autosave"))
        self.chB_dataset_save_img.setText(_translate("MainWindow", "save img"))
        self.chB_load_after_meas.setText(_translate("MainWindow", "load after meas"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Loading"))
        self.pB_replay_goto_end.setStatusTip(_translate("MainWindow", "Display last meas. frame (End)"))
        self.pB_replay_goto_end.setShortcut(_translate("MainWindow", "End"))
        self.pB_replay_play.setStatusTip(_translate("MainWindow", "Start Replay pf measurements (Ctrl +Space)"))
        self.pB_replay_play.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.pB_replay_back_begin.setStatusTip(_translate("MainWindow", "Display last meas. frame (Pos1)"))
        self.pB_replay_back_begin.setShortcut(_translate("MainWindow", "Home"))
        self.sB_replay_time.setSuffix(_translate("MainWindow", " s"))
        self.lab_replay_time.setText(_translate("MainWindow", "Refresh time"))
        self.pB_load_meas_dataset.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_load_meas_dataset.setText(_translate("MainWindow", "Load measurements"))
        self.lab_replay_status.setText(_translate("MainWindow", "Replay status"))
        self.tE_load_dataset_dir.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">default_</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">loading_</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dirpath</p></body></html>"))
        self.pB_export_meas_csv.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_export_meas_csv.setText(_translate("MainWindow", "Export measurements to CSV"))
        self.pB_load_ref_dataset.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_load_ref_dataset.setText(_translate("MainWindow", "Load reference dataset"))
        self.pB_load_eidors_fwd_solution.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_load_eidors_fwd_solution.setText(_translate("MainWindow", "Load EIDORS fwd solution"))
        self.pB_export_data_meas_vs_eidors.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_export_data_meas_vs_eidors.setText(_translate("MainWindow", "Export measurements vs EIDORS to CSV"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_measurements), _translate("MainWindow", "Measurements"))
        self.label_vmax_7.setText(_translate("MainWindow", "p"))
        self.label_vmax_8.setText(_translate("MainWindow", "lamda"))
        self.label_vmax_9.setText(_translate("MainWindow", "n"))
        self.label_FEMRefinement.setText(_translate("MainWindow", "FEM Refinement"))
        self.label_FEMRefinement_2.setText(_translate("MainWindow", "BackGround"))
        self.lab_solver.setText(_translate("MainWindow", "Solver"))
        self.normalize.setText(_translate("MainWindow", "Normalize"))
        self.tabW_reconstruction.setTabText(self.tabW_reconstruction.indexOf(self.tab_pyeit), _translate("MainWindow", "PyEIT"))
        self.lE_load_model_dir.setText(_translate("MainWindow", "default_loading_dirpath"))
        self.tabW_reconstruction.setTabText(self.tabW_reconstruction.indexOf(self.tab_nn), _translate("MainWindow", "NN"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Imaging type"))
        self.lab_ref_frame_idx.setText(_translate("MainWindow", "Reference frame#"))
        self.lab_freq_meas_0.setText(_translate("MainWindow", "Frequence"))
        self.lab_freq_meas_1.setText(_translate("MainWindow", "Frequence "))
        self.showAbsValue.setText(_translate("MainWindow", "Show absolute values"))
        self.label_vmax.setText(_translate("MainWindow", "vmax"))
        self.label_vmin.setText(_translate("MainWindow", "vmin"))
        self.pB_set_reconstruction.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_set_reconstruction.setText(_translate("MainWindow", "Set reconstruction"))
        self.lab_log_level.setText(_translate("MainWindow", "log level"))
        self.cB_log_level.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.lab_eit_mdl_ctlg.setText(_translate("MainWindow", "log level"))
        self.pB_refresh_eit_mdl_ctlg.setStatusTip(_translate("MainWindow", "Save dataset to file (*.dat)"))
        self.pB_refresh_eit_mdl_ctlg.setText(_translate("MainWindow", "Refresh catalogue"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_eit_model), _translate("MainWindow", "EIT:_model"))
        self.cB_video_devices.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_refresh_video_devices.setToolTip(_translate("MainWindow", "test"))
        self.pB_refresh_video_devices.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_refresh_video_devices.setText(_translate("MainWindow", "Refresh"))
        self.pB_capture_start.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_start.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_start.setText(_translate("MainWindow", "Start capture"))
        self.pB_capture_stop.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_stop.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_stop.setText(_translate("MainWindow", "Stop capture"))
        self.pB_capture_snapshot.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_snapshot.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_snapshot.setText(_translate("MainWindow", "Snapshot"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_video), _translate("MainWindow", "Video"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Video"))
        self.video_frame.setText(_translate("MainWindow", "Live Video"))
        self.video_frame_miniature.setText(_translate("MainWindow", "Live Video"))
        self.pB_somahey.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Reconstruction"))
        self.chB_plot_image_rec.setText(_translate("MainWindow", "Image"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Graph"))
        self.chB_y_log.setText(_translate("MainWindow", "y log"))
        self.chB_plot_graph.setText(_translate("MainWindow", "Graph"))
        self.chB_diff.setText(_translate("MainWindow", "Difference"))
        self.chB_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab_meas_voltages), _translate("MainWindow", "Reconstruction data"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_Z), _translate("MainWindow", "Z"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_real), _translate("MainWindow", "Real"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_imag), _translate("MainWindow", "Imag"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_phase), _translate("MainWindow", "Phase"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_magnitude), _translate("MainWindow", "Magnitude"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab_values), _translate("MainWindow", "Measured values tabs"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab), _translate("MainWindow", "Measured values graph"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
