# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eit_app/gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1927, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/EIT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabW_settings = QtWidgets.QTabWidget(self.centralwidget)
        self.tabW_settings.setGeometry(QtCore.QRect(10, 10, 431, 1021))
        self.tabW_settings.setObjectName("tabW_settings")
        self.tab_device = QtWidgets.QWidget()
        self.tab_device.setObjectName("tab_device")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_device)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 401, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(10, 20, 381, 81))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pB_refresh = QtWidgets.QPushButton(self.widget)
        self.pB_refresh.setEnabled(True)
        self.pB_refresh.setToolTip("")
        self.pB_refresh.setAutoFillBackground(False)
        self.pB_refresh.setObjectName("pB_refresh")
        self.gridLayout_6.addWidget(self.pB_refresh, 0, 0, 1, 1)
        self.pB_connect = QtWidgets.QPushButton(self.widget)
        self.pB_connect.setAutoFillBackground(False)
        self.pB_connect.setObjectName("pB_connect")
        self.gridLayout_6.addWidget(self.pB_connect, 0, 1, 1, 1)
        self.pB_disconnect = QtWidgets.QPushButton(self.widget)
        self.pB_disconnect.setToolTip("")
        self.pB_disconnect.setAutoFillBackground(False)
        self.pB_disconnect.setObjectName("pB_disconnect")
        self.gridLayout_6.addWidget(self.pB_disconnect, 0, 2, 1, 1)
        self.cB_ports = QtWidgets.QComboBox(self.widget)
        self.cB_ports.setToolTip("")
        self.cB_ports.setObjectName("cB_ports")
        self.gridLayout_6.addWidget(self.cB_ports, 1, 0, 1, 3)
        self.lab_device_status = QtWidgets.QLabel(self.widget)
        self.lab_device_status.setStatusTip("")
        self.lab_device_status.setAutoFillBackground(True)
        self.lab_device_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_device_status.setObjectName("lab_device_status")
        self.gridLayout_6.addWidget(self.lab_device_status, 2, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_device)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 130, 401, 531))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 61, 231, 381))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.LayoutParameters = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.LayoutParameters.setContentsMargins(0, 0, 0, 0)
        self.LayoutParameters.setHorizontalSpacing(6)
        self.LayoutParameters.setObjectName("LayoutParameters")
        self.lab_exc_amp = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_exc_amp.setObjectName("lab_exc_amp")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lab_exc_amp)
        self.sBd_exc_amp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_exc_amp.setDecimals(4)
        self.sBd_exc_amp.setMinimum(0.0001)
        self.sBd_exc_amp.setMaximum(10.0)
        self.sBd_exc_amp.setSingleStep(0.1)
        self.sBd_exc_amp.setObjectName("sBd_exc_amp")
        self.LayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBd_exc_amp)
        self.lab_burst = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_burst.setObjectName("lab_burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lab_burst)
        self.sB_burst = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_burst.setMaximum(255)
        self.sB_burst.setObjectName("sB_burst")
        self.LayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_burst)
        self.lab_minF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_minF.setObjectName("lab_minF")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lab_minF)
        self.sBd_freq_min = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_min.setMinimum(100.0)
        self.sBd_freq_min.setMaximum(1000000.0)
        self.sBd_freq_min.setObjectName("sBd_freq_min")
        self.LayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_min)
        self.lab_maxF = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_maxF.setObjectName("lab_maxF")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lab_maxF)
        self.sBd_freq_max = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_freq_max.setAutoFillBackground(False)
        self.sBd_freq_max.setMinimum(100.0)
        self.sBd_freq_max.setMaximum(1000000.0)
        self.sBd_freq_max.setObjectName("sBd_freq_max")
        self.LayoutParameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sBd_freq_max)
        self.lab_steps = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_steps.setObjectName("lab_steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lab_steps)
        self.sB_freq_steps = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.sB_freq_steps.setMinimum(1)
        self.sB_freq_steps.setMaximum(255)
        self.sB_freq_steps.setObjectName("sB_freq_steps")
        self.LayoutParameters.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sB_freq_steps)
        self.lab_scale = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_scale.setObjectName("lab_scale")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lab_scale)
        self.cB_scale = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cB_scale.setEditable(False)
        self.cB_scale.setMaxVisibleItems(2)
        self.cB_scale.setObjectName("cB_scale")
        self.LayoutParameters.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cB_scale)
        self.lab_frame_rate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_frame_rate.setObjectName("lab_frame_rate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lab_frame_rate)
        self.sBd_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_frame_rate.setDecimals(3)
        self.sBd_frame_rate.setMaximum(100.0)
        self.sBd_frame_rate.setSingleStep(0.001)
        self.sBd_frame_rate.setObjectName("sBd_frame_rate")
        self.LayoutParameters.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sBd_frame_rate)
        self.lab_max_frame_rate = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_max_frame_rate.setObjectName("lab_max_frame_rate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lab_max_frame_rate)
        self.sBd_max_frame_rate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.sBd_max_frame_rate.setEnabled(False)
        self.sBd_max_frame_rate.setDecimals(3)
        self.sBd_max_frame_rate.setMaximum(100.0)
        self.sBd_max_frame_rate.setSingleStep(0.001)
        self.sBd_max_frame_rate.setObjectName("sBd_max_frame_rate")
        self.LayoutParameters.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sBd_max_frame_rate)
        self.lab_sn = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_sn.setObjectName("lab_sn")
        self.LayoutParameters.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lab_sn)
        self.lE_sn = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_sn.setEnabled(False)
        self.lE_sn.setToolTip("")
        self.lE_sn.setWhatsThis("")
        self.lE_sn.setInputMask("")
        self.lE_sn.setFrame(True)
        self.lE_sn.setObjectName("lE_sn")
        self.LayoutParameters.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lE_sn)
        self.lab_ip = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_ip.setObjectName("lab_ip")
        self.LayoutParameters.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lab_ip)
        self.lE_ip = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_ip.setToolTip("")
        self.lE_ip.setWhatsThis("")
        self.lE_ip.setInputMask("")
        self.lE_ip.setFrame(True)
        self.lE_ip.setObjectName("lE_ip")
        self.LayoutParameters.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lE_ip)
        self.lab_mac = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_mac.setObjectName("lab_mac")
        self.LayoutParameters.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lab_mac)
        self.lE_mac = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lE_mac.setEnabled(False)
        self.lE_mac.setObjectName("lE_mac")
        self.LayoutParameters.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lE_mac)
        self.chB_dhcp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_dhcp.setEnabled(False)
        self.chB_dhcp.setChecked(False)
        self.chB_dhcp.setObjectName("chB_dhcp")
        self.LayoutParameters.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.chB_dhcp)
        self.chB_exc_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_exc_stamp.setEnabled(False)
        self.chB_exc_stamp.setChecked(True)
        self.chB_exc_stamp.setObjectName("chB_exc_stamp")
        self.LayoutParameters.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.chB_exc_stamp)
        self.chB_current_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_current_stamp.setEnabled(False)
        self.chB_current_stamp.setChecked(True)
        self.chB_current_stamp.setObjectName("chB_current_stamp")
        self.LayoutParameters.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.chB_current_stamp)
        self.chB_time_stamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chB_time_stamp.setEnabled(False)
        self.chB_time_stamp.setChecked(True)
        self.chB_time_stamp.setObjectName("chB_time_stamp")
        self.LayoutParameters.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.chB_time_stamp)
        self.lab_output_config = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lab_output_config.setObjectName("lab_output_config")
        self.LayoutParameters.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lab_output_config)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(250, 61, 141, 381))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(8, 20, 131, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_exc_chip = QtWidgets.QWidget()
        self.tab_exc_chip.setObjectName("tab_exc_chip")
        self.tw_exc_mat_chip = QtWidgets.QTableWidget(self.tab_exc_chip)
        self.tw_exc_mat_chip.setGeometry(QtCore.QRect(0, 0, 121, 321))
        self.tw_exc_mat_chip.setObjectName("tw_exc_mat_chip")
        self.tw_exc_mat_chip.setColumnCount(2)
        self.tw_exc_mat_chip.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_mat_chip.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_mat_chip.setHorizontalHeaderItem(1, item)
        self.tw_exc_mat_chip.horizontalHeader().setDefaultSectionSize(40)
        self.tabWidget.addTab(self.tab_exc_chip, "")
        self.tab_exc_model = QtWidgets.QWidget()
        self.tab_exc_model.setObjectName("tab_exc_model")
        self.tw_exc_mat_model = QtWidgets.QTableWidget(self.tab_exc_model)
        self.tw_exc_mat_model.setGeometry(QtCore.QRect(0, 0, 121, 321))
        self.tw_exc_mat_model.setObjectName("tw_exc_mat_model")
        self.tw_exc_mat_model.setColumnCount(2)
        self.tw_exc_mat_model.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_mat_model.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_exc_mat_model.setHorizontalHeaderItem(1, item)
        self.tw_exc_mat_model.horizontalHeader().setDefaultSectionSize(40)
        self.tabWidget.addTab(self.tab_exc_model, "")
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(10, 490, 381, 25))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pB_load_setup = QtWidgets.QPushButton(self.widget1)
        self.pB_load_setup.setAutoFillBackground(False)
        self.pB_load_setup.setObjectName("pB_load_setup")
        self.gridLayout_4.addWidget(self.pB_load_setup, 0, 0, 1, 1)
        self.pB_save_setup = QtWidgets.QPushButton(self.widget1)
        self.pB_save_setup.setAutoFillBackground(False)
        self.pB_save_setup.setObjectName("pB_save_setup")
        self.gridLayout_4.addWidget(self.pB_save_setup, 0, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.groupBox_4)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 381, 25))
        self.widget2.setObjectName("widget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pB_set_setup = QtWidgets.QPushButton(self.widget2)
        self.pB_set_setup.setEnabled(True)
        self.pB_set_setup.setAutoFillBackground(False)
        self.pB_set_setup.setObjectName("pB_set_setup")
        self.gridLayout_5.addWidget(self.pB_set_setup, 0, 0, 1, 1)
        self.pB_get_setup = QtWidgets.QPushButton(self.widget2)
        self.pB_get_setup.setAutoFillBackground(False)
        self.pB_get_setup.setObjectName("pB_get_setup")
        self.gridLayout_5.addWidget(self.pB_get_setup, 0, 1, 1, 1)
        self.pB_reset = QtWidgets.QPushButton(self.widget2)
        self.pB_reset.setAutoFillBackground(False)
        self.pB_reset.setObjectName("pB_reset")
        self.gridLayout_5.addWidget(self.pB_reset, 0, 2, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.groupBox_4)
        self.widget3.setGeometry(QtCore.QRect(10, 450, 381, 25))
        self.widget3.setObjectName("widget3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lab_chip = QtWidgets.QLabel(self.widget3)
        self.lab_chip.setObjectName("lab_chip")
        self.gridLayout_8.addWidget(self.lab_chip, 0, 0, 1, 1)
        self.cB_chip_ctlg = QtWidgets.QComboBox(self.widget3)
        self.cB_chip_ctlg.setEditable(False)
        self.cB_chip_ctlg.setMaxVisibleItems(2)
        self.cB_chip_ctlg.setObjectName("cB_chip_ctlg")
        self.gridLayout_8.addWidget(self.cB_chip_ctlg, 0, 1, 1, 1)
        self.pB_chip_refresh_ctlg = QtWidgets.QPushButton(self.widget3)
        self.pB_chip_refresh_ctlg.setAutoFillBackground(False)
        self.pB_chip_refresh_ctlg.setObjectName("pB_chip_refresh_ctlg")
        self.gridLayout_8.addWidget(self.pB_chip_refresh_ctlg, 0, 2, 1, 1)
        self.gridLayout_8.setColumnMinimumWidth(1, 300)
        self.tabW_settings.addTab(self.tab_device, "")
        self.tab_measurements = QtWidgets.QWidget()
        self.tab_measurements.setObjectName("tab_measurements")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 401, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tE_frame_info = QtWidgets.QTextEdit(self.groupBox_2)
        self.tE_frame_info.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.tE_frame_info.setObjectName("tE_frame_info")
        self.pB_load_eidors_fwd_solution = QtWidgets.QPushButton(self.tab_measurements)
        self.pB_load_eidors_fwd_solution.setGeometry(QtCore.QRect(10, 600, 181, 23))
        self.pB_load_eidors_fwd_solution.setAutoFillBackground(False)
        self.pB_load_eidors_fwd_solution.setObjectName("pB_load_eidors_fwd_solution")
        self.sB_eidors_factor = QtWidgets.QDoubleSpinBox(self.tab_measurements)
        self.sB_eidors_factor.setGeometry(QtCore.QRect(290, 600, 91, 23))
        self.sB_eidors_factor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sB_eidors_factor.setSuffix("")
        self.sB_eidors_factor.setDecimals(3)
        self.sB_eidors_factor.setMinimum(-1000000.0)
        self.sB_eidors_factor.setMaximum(1000000.0)
        self.sB_eidors_factor.setSingleStep(0.1)
        self.sB_eidors_factor.setProperty("value", 1.0)
        self.sB_eidors_factor.setObjectName("sB_eidors_factor")
        self.pB_export_data_meas_vs_eidors = QtWidgets.QPushButton(self.tab_measurements)
        self.pB_export_data_meas_vs_eidors.setGeometry(QtCore.QRect(10, 630, 231, 23))
        self.pB_export_data_meas_vs_eidors.setAutoFillBackground(False)
        self.pB_export_data_meas_vs_eidors.setObjectName("pB_export_data_meas_vs_eidors")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 660, 411, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 391, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.cB_eit_imaging_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cB_eit_imaging_type.setCurrentText("")
        self.cB_eit_imaging_type.setObjectName("cB_eit_imaging_type")
        self.gridLayout.addWidget(self.cB_eit_imaging_type, 0, 0, 1, 5)
        self.cB_eit_imaging_meas_freq = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_eit_imaging_meas_freq.sizePolicy().hasHeightForWidth())
        self.cB_eit_imaging_meas_freq.setSizePolicy(sizePolicy)
        self.cB_eit_imaging_meas_freq.setMinimumSize(QtCore.QSize(78, 0))
        self.cB_eit_imaging_meas_freq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cB_eit_imaging_meas_freq.setObjectName("cB_eit_imaging_meas_freq")
        self.gridLayout.addWidget(self.cB_eit_imaging_meas_freq, 2, 2, 1, 2)
        self.lab_ref_frame_idx = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_ref_frame_idx.sizePolicy().hasHeightForWidth())
        self.lab_ref_frame_idx.setSizePolicy(sizePolicy)
        self.lab_ref_frame_idx.setObjectName("lab_ref_frame_idx")
        self.gridLayout.addWidget(self.lab_ref_frame_idx, 1, 4, 1, 1)
        self.cB_eit_imaging_ref_frame = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_eit_imaging_ref_frame.sizePolicy().hasHeightForWidth())
        self.cB_eit_imaging_ref_frame.setSizePolicy(sizePolicy)
        self.cB_eit_imaging_ref_frame.setMinimumSize(QtCore.QSize(78, 0))
        self.cB_eit_imaging_ref_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cB_eit_imaging_ref_frame.setObjectName("cB_eit_imaging_ref_frame")
        self.gridLayout.addWidget(self.cB_eit_imaging_ref_frame, 2, 4, 1, 1)
        self.lab_freq_meas_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_freq_meas_0.setObjectName("lab_freq_meas_0")
        self.gridLayout.addWidget(self.lab_freq_meas_0, 1, 0, 1, 2)
        self.lab_freq_meas_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_freq_meas_1.sizePolicy().hasHeightForWidth())
        self.lab_freq_meas_1.setSizePolicy(sizePolicy)
        self.lab_freq_meas_1.setObjectName("lab_freq_meas_1")
        self.gridLayout.addWidget(self.lab_freq_meas_1, 1, 2, 1, 2)
        self.cB_eit_imaging_ref_freq = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_eit_imaging_ref_freq.sizePolicy().hasHeightForWidth())
        self.cB_eit_imaging_ref_freq.setSizePolicy(sizePolicy)
        self.cB_eit_imaging_ref_freq.setCurrentText("")
        self.cB_eit_imaging_ref_freq.setObjectName("cB_eit_imaging_ref_freq")
        self.gridLayout.addWidget(self.cB_eit_imaging_ref_freq, 2, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 260, 60))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chB_eit_imaging_trans_abs = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.chB_eit_imaging_trans_abs.setObjectName("chB_eit_imaging_trans_abs")
        self.gridLayout_2.addWidget(self.chB_eit_imaging_trans_abs, 1, 0, 1, 1)
        self.cB_eit_imaging_trans = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cB_eit_imaging_trans.setCurrentText("")
        self.cB_eit_imaging_trans.setObjectName("cB_eit_imaging_trans")
        self.gridLayout_2.addWidget(self.cB_eit_imaging_trans, 0, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.tab_measurements)
        self.toolBox.setGeometry(QtCore.QRect(10, 12, 411, 301))
        self.toolBox.setObjectName("toolBox")
        self.Acquisition = QtWidgets.QWidget()
        self.Acquisition.setGeometry(QtCore.QRect(0, 0, 411, 247))
        self.Acquisition.setObjectName("Acquisition")
        self.lab_actual_frame_cnt = QtWidgets.QLabel(self.Acquisition)
        self.lab_actual_frame_cnt.setGeometry(QtCore.QRect(20, 100, 141, 23))
        self.lab_actual_frame_cnt.setObjectName("lab_actual_frame_cnt")
        self.chB_dataset_autosave = QtWidgets.QCheckBox(self.Acquisition)
        self.chB_dataset_autosave.setGeometry(QtCore.QRect(20, 60, 71, 23))
        self.chB_dataset_autosave.setChecked(True)
        self.chB_dataset_autosave.setObjectName("chB_dataset_autosave")
        self.chB_dataset_save_img = QtWidgets.QCheckBox(self.Acquisition)
        self.chB_dataset_save_img.setGeometry(QtCore.QRect(100, 60, 71, 23))
        self.chB_dataset_save_img.setChecked(True)
        self.chB_dataset_save_img.setObjectName("chB_dataset_save_img")
        self.sB_actual_frame_cnt = QtWidgets.QSpinBox(self.Acquisition)
        self.sB_actual_frame_cnt.setEnabled(True)
        self.sB_actual_frame_cnt.setGeometry(QtCore.QRect(170, 100, 51, 23))
        self.sB_actual_frame_cnt.setFrame(True)
        self.sB_actual_frame_cnt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sB_actual_frame_cnt.setMaximum(999)
        self.sB_actual_frame_cnt.setObjectName("sB_actual_frame_cnt")
        self.pB_start_meas = QtWidgets.QPushButton(self.Acquisition)
        self.pB_start_meas.setGeometry(QtCore.QRect(20, 0, 121, 23))
        self.pB_start_meas.setAutoFillBackground(False)
        self.pB_start_meas.setObjectName("pB_start_meas")
        self.lab_live_meas_status = QtWidgets.QLabel(self.Acquisition)
        self.lab_live_meas_status.setGeometry(QtCore.QRect(280, 0, 121, 23))
        self.lab_live_meas_status.setAutoFillBackground(True)
        self.lab_live_meas_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_live_meas_status.setObjectName("lab_live_meas_status")
        self.lE_meas_dataset_dir = QtWidgets.QLineEdit(self.Acquisition)
        self.lE_meas_dataset_dir.setGeometry(QtCore.QRect(20, 30, 380, 23))
        self.lE_meas_dataset_dir.setObjectName("lE_meas_dataset_dir")
        self.pB_stop_meas = QtWidgets.QPushButton(self.Acquisition)
        self.pB_stop_meas.setGeometry(QtCore.QRect(150, 0, 121, 23))
        self.pB_stop_meas.setAutoFillBackground(False)
        self.pB_stop_meas.setObjectName("pB_stop_meas")
        self.chB_load_after_meas = QtWidgets.QCheckBox(self.Acquisition)
        self.chB_load_after_meas.setGeometry(QtCore.QRect(170, 60, 101, 23))
        self.chB_load_after_meas.setChecked(True)
        self.chB_load_after_meas.setObjectName("chB_load_after_meas")
        self.meas_progress_bar = QtWidgets.QProgressBar(self.Acquisition)
        self.meas_progress_bar.setGeometry(QtCore.QRect(230, 100, 171, 23))
        self.meas_progress_bar.setProperty("value", 0)
        self.meas_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.meas_progress_bar.setObjectName("meas_progress_bar")
        self.toolBox.addItem(self.Acquisition, "")
        self.Replay = QtWidgets.QWidget()
        self.Replay.setGeometry(QtCore.QRect(0, 0, 411, 247))
        self.Replay.setObjectName("Replay")
        self.pB_export_meas_csv = QtWidgets.QPushButton(self.Replay)
        self.pB_export_meas_csv.setGeometry(QtCore.QRect(10, 210, 181, 23))
        self.pB_export_meas_csv.setAutoFillBackground(False)
        self.pB_export_meas_csv.setObjectName("pB_export_meas_csv")
        self.slider_replay = QtWidgets.QSlider(self.Replay)
        self.slider_replay.setGeometry(QtCore.QRect(10, 180, 381, 23))
        self.slider_replay.setOrientation(QtCore.Qt.Horizontal)
        self.slider_replay.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_replay.setTickInterval(0)
        self.slider_replay.setObjectName("slider_replay")
        self.sB_replay_time = QtWidgets.QDoubleSpinBox(self.Replay)
        self.sB_replay_time.setGeometry(QtCore.QRect(320, 140, 55, 20))
        self.sB_replay_time.setDecimals(1)
        self.sB_replay_time.setMinimum(0.1)
        self.sB_replay_time.setMaximum(10.0)
        self.sB_replay_time.setSingleStep(0.1)
        self.sB_replay_time.setProperty("value", 1.0)
        self.sB_replay_time.setObjectName("sB_replay_time")
        self.pB_load_ref_dataset = QtWidgets.QPushButton(self.Replay)
        self.pB_load_ref_dataset.setGeometry(QtCore.QRect(200, 210, 181, 23))
        self.pB_load_ref_dataset.setAutoFillBackground(False)
        self.pB_load_ref_dataset.setObjectName("pB_load_ref_dataset")
        self.cB_replay_frame_idx = QtWidgets.QComboBox(self.Replay)
        self.cB_replay_frame_idx.setGeometry(QtCore.QRect(120, 140, 66, 20))
        self.cB_replay_frame_idx.setObjectName("cB_replay_frame_idx")
        self.splitter = QtWidgets.QSplitter(self.Replay)
        self.splitter.setGeometry(QtCore.QRect(10, 100, 381, 25))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pB_replay_begin = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_begin.setAutoFillBackground(False)
        self.pB_replay_begin.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icon_begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_begin.setIcon(icon1)
        self.pB_replay_begin.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_begin.setCheckable(False)
        self.pB_replay_begin.setChecked(False)
        self.pB_replay_begin.setAutoDefault(False)
        self.pB_replay_begin.setFlat(False)
        self.pB_replay_begin.setObjectName("pB_replay_begin")
        self.pB_replay_back = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_back.setAutoFillBackground(False)
        self.pB_replay_back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icon_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_back.setIcon(icon2)
        self.pB_replay_back.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_back.setCheckable(False)
        self.pB_replay_back.setAutoDefault(False)
        self.pB_replay_back.setFlat(False)
        self.pB_replay_back.setObjectName("pB_replay_back")
        self.pB_replay_play = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_play.setAutoFillBackground(False)
        self.pB_replay_play.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icon_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_play.setIcon(icon3)
        self.pB_replay_play.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_play.setCheckable(False)
        self.pB_replay_play.setAutoDefault(False)
        self.pB_replay_play.setFlat(False)
        self.pB_replay_play.setObjectName("pB_replay_play")
        self.pB_replay_next = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_next.setAutoFillBackground(False)
        self.pB_replay_next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icon_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_next.setIcon(icon4)
        self.pB_replay_next.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_next.setCheckable(False)
        self.pB_replay_next.setAutoDefault(False)
        self.pB_replay_next.setFlat(False)
        self.pB_replay_next.setObjectName("pB_replay_next")
        self.pB_replay_end = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_end.setAutoFillBackground(False)
        self.pB_replay_end.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icon_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_end.setIcon(icon5)
        self.pB_replay_end.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_end.setAutoDefault(False)
        self.pB_replay_end.setFlat(False)
        self.pB_replay_end.setObjectName("pB_replay_end")
        self.pB_replay_stop = QtWidgets.QPushButton(self.splitter)
        self.pB_replay_stop.setAutoFillBackground(False)
        self.pB_replay_stop.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icon_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_replay_stop.setIcon(icon6)
        self.pB_replay_stop.setIconSize(QtCore.QSize(32, 16))
        self.pB_replay_stop.setAutoDefault(False)
        self.pB_replay_stop.setFlat(False)
        self.pB_replay_stop.setObjectName("pB_replay_stop")
        self.lab_replay_time = QtWidgets.QLabel(self.Replay)
        self.lab_replay_time.setGeometry(QtCore.QRect(240, 140, 61, 16))
        self.lab_replay_time.setObjectName("lab_replay_time")
        self.tE_load_dataset_dir = QtWidgets.QTextEdit(self.Replay)
        self.tE_load_dataset_dir.setEnabled(True)
        self.tE_load_dataset_dir.setGeometry(QtCore.QRect(10, 30, 381, 50))
        self.tE_load_dataset_dir.setObjectName("tE_load_dataset_dir")
        self.lab_replay_status = QtWidgets.QLabel(self.Replay)
        self.lab_replay_status.setGeometry(QtCore.QRect(210, 0, 181, 23))
        self.lab_replay_status.setAutoFillBackground(True)
        self.lab_replay_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_replay_status.setObjectName("lab_replay_status")
        self.lab_current_frame_indx = QtWidgets.QLabel(self.Replay)
        self.lab_current_frame_indx.setGeometry(QtCore.QRect(20, 140, 101, 20))
        self.lab_current_frame_indx.setObjectName("lab_current_frame_indx")
        self.pB_meas_dataset_load = QtWidgets.QPushButton(self.Replay)
        self.pB_meas_dataset_load.setGeometry(QtCore.QRect(10, 0, 181, 23))
        self.pB_meas_dataset_load.setAutoFillBackground(False)
        self.pB_meas_dataset_load.setObjectName("pB_meas_dataset_load")
        self.toolBox.addItem(self.Replay, "")
        self.tabW_settings.addTab(self.tab_measurements, "")
        self.tab_eit_model = QtWidgets.QWidget()
        self.tab_eit_model.setObjectName("tab_eit_model")
        self.tabW_reconstruction = QtWidgets.QTabWidget(self.tab_eit_model)
        self.tabW_reconstruction.setGeometry(QtCore.QRect(10, 110, 411, 271))
        self.tabW_reconstruction.setObjectName("tabW_reconstruction")
        self.tab_pyeit = QtWidgets.QWidget()
        self.tab_pyeit.setObjectName("tab_pyeit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_pyeit)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 10, 281, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 238, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lab_solver = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lab_solver.setObjectName("lab_solver")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lab_solver)
        self.cB_pyeit_solver = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.cB_pyeit_solver.setObjectName("cB_pyeit_solver")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cB_pyeit_solver)
        self.label_vmax_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_7.setObjectName("label_vmax_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_vmax_7)
        self.sBd_pyeit_p = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.sBd_pyeit_p.setDecimals(1)
        self.sBd_pyeit_p.setMinimum(-1000000000000000.0)
        self.sBd_pyeit_p.setMaximum(1000000000000000.0)
        self.sBd_pyeit_p.setProperty("value", 0.5)
        self.sBd_pyeit_p.setObjectName("sBd_pyeit_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sBd_pyeit_p)
        self.label_vmax_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_8.setObjectName("label_vmax_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_vmax_8)
        self.sBd_pyeit_lamda = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.sBd_pyeit_lamda.setDecimals(4)
        self.sBd_pyeit_lamda.setMinimum(-1000000000000000.0)
        self.sBd_pyeit_lamda.setMaximum(1000000000000000.0)
        self.sBd_pyeit_lamda.setProperty("value", 0.01)
        self.sBd_pyeit_lamda.setObjectName("sBd_pyeit_lamda")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sBd_pyeit_lamda)
        self.label_vmax_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_vmax_9.setObjectName("label_vmax_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_vmax_9)
        self.sBd_pyeit_greit_n = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.sBd_pyeit_greit_n.setDecimals(0)
        self.sBd_pyeit_greit_n.setMinimum(-1000000000000000.0)
        self.sBd_pyeit_greit_n.setMaximum(1000000000000000.0)
        self.sBd_pyeit_greit_n.setProperty("value", 64.0)
        self.sBd_pyeit_greit_n.setObjectName("sBd_pyeit_greit_n")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sBd_pyeit_greit_n)
        self.label_FEMRefinement_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_FEMRefinement_2.setObjectName("label_FEMRefinement_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_FEMRefinement_2)
        self.sBd_pyeit_bckgrnd = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.sBd_pyeit_bckgrnd.setDecimals(4)
        self.sBd_pyeit_bckgrnd.setMaximum(10.0)
        self.sBd_pyeit_bckgrnd.setSingleStep(0.001)
        self.sBd_pyeit_bckgrnd.setProperty("value", 0.1)
        self.sBd_pyeit_bckgrnd.setObjectName("sBd_pyeit_bckgrnd")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sBd_pyeit_bckgrnd)
        self.tabW_reconstruction.addTab(self.tab_pyeit, "")
        self.tab_nn = QtWidgets.QWidget()
        self.tab_nn.setObjectName("tab_nn")
        self.lE_ai_model_dir = QtWidgets.QLineEdit(self.tab_nn)
        self.lE_ai_model_dir.setEnabled(False)
        self.lE_ai_model_dir.setGeometry(QtCore.QRect(10, 20, 390, 23))
        self.lE_ai_model_dir.setObjectName("lE_ai_model_dir")
        self.tabW_reconstruction.addTab(self.tab_nn, "")
        self.pB_set_reconstruction = QtWidgets.QPushButton(self.tab_eit_model)
        self.pB_set_reconstruction.setGeometry(QtCore.QRect(290, 100, 121, 23))
        self.pB_set_reconstruction.setAutoFillBackground(False)
        self.pB_set_reconstruction.setObjectName("pB_set_reconstruction")
        self.sBd_eit_model_fem_refinement = QtWidgets.QDoubleSpinBox(self.tab_eit_model)
        self.sBd_eit_model_fem_refinement.setGeometry(QtCore.QRect(130, 40, 152, 20))
        self.sBd_eit_model_fem_refinement.setDecimals(4)
        self.sBd_eit_model_fem_refinement.setMinimum(0.0)
        self.sBd_eit_model_fem_refinement.setMaximum(10.0)
        self.sBd_eit_model_fem_refinement.setSingleStep(0.001)
        self.sBd_eit_model_fem_refinement.setProperty("value", 0.1)
        self.sBd_eit_model_fem_refinement.setObjectName("sBd_eit_model_fem_refinement")
        self.label_FEMRefinement = QtWidgets.QLabel(self.tab_eit_model)
        self.label_FEMRefinement.setGeometry(QtCore.QRect(46, 40, 78, 20))
        self.label_FEMRefinement.setObjectName("label_FEMRefinement")
        self.chB_eit_mdl_normalize = QtWidgets.QCheckBox(self.tab_eit_model)
        self.chB_eit_mdl_normalize.setGeometry(QtCore.QRect(40, 80, 69, 17))
        self.chB_eit_mdl_normalize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chB_eit_mdl_normalize.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.chB_eit_mdl_normalize.setObjectName("chB_eit_mdl_normalize")
        self.widget4 = QtWidgets.QWidget(self.tab_eit_model)
        self.widget4.setGeometry(QtCore.QRect(20, 10, 391, 25))
        self.widget4.setObjectName("widget4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lab_eit_mdl_ctlg = QtWidgets.QLabel(self.widget4)
        self.lab_eit_mdl_ctlg.setObjectName("lab_eit_mdl_ctlg")
        self.gridLayout_7.addWidget(self.lab_eit_mdl_ctlg, 0, 0, 1, 1)
        self.cB_eit_mdl_ctlg = QtWidgets.QComboBox(self.widget4)
        self.cB_eit_mdl_ctlg.setCurrentText("")
        self.cB_eit_mdl_ctlg.setObjectName("cB_eit_mdl_ctlg")
        self.gridLayout_7.addWidget(self.cB_eit_mdl_ctlg, 0, 1, 1, 1)
        self.pB_eit_mdl_refresh_ctlg = QtWidgets.QPushButton(self.widget4)
        self.pB_eit_mdl_refresh_ctlg.setAutoFillBackground(False)
        self.pB_eit_mdl_refresh_ctlg.setObjectName("pB_eit_mdl_refresh_ctlg")
        self.gridLayout_7.addWidget(self.pB_eit_mdl_refresh_ctlg, 0, 2, 1, 1)
        self.gridLayout_7.setColumnMinimumWidth(1, 300)
        self.widget5 = QtWidgets.QWidget(self.tab_eit_model)
        self.widget5.setGeometry(QtCore.QRect(20, 410, 231, 22))
        self.widget5.setObjectName("widget5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lab_log_level = QtWidgets.QLabel(self.widget5)
        self.lab_log_level.setObjectName("lab_log_level")
        self.gridLayout_9.addWidget(self.lab_log_level, 0, 0, 1, 1)
        self.cB_log_level = QtWidgets.QComboBox(self.widget5)
        self.cB_log_level.setToolTip("")
        self.cB_log_level.setObjectName("cB_log_level")
        self.gridLayout_9.addWidget(self.cB_log_level, 0, 1, 1, 1)
        self.tabW_settings.addTab(self.tab_eit_model, "")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(1260, 0, 661, 561))
        self.groupBox_7.setObjectName("groupBox_7")
        self.video_frame = QtWidgets.QLabel(self.groupBox_7)
        self.video_frame.setGeometry(QtCore.QRect(10, 79, 640, 471))
        self.video_frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_frame.setMouseTracking(True)
        self.video_frame.setAutoFillBackground(False)
        self.video_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame.setObjectName("video_frame")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 641, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cB_capture_devices = QtWidgets.QComboBox(self.layoutWidget)
        self.cB_capture_devices.setToolTip("")
        self.cB_capture_devices.setEditable(False)
        self.cB_capture_devices.setObjectName("cB_capture_devices")
        self.gridLayout_3.addWidget(self.cB_capture_devices, 0, 0, 1, 1)
        self.pB_capture_connect = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_capture_connect.setEnabled(True)
        self.pB_capture_connect.setAutoFillBackground(False)
        self.pB_capture_connect.setObjectName("pB_capture_connect")
        self.gridLayout_3.addWidget(self.pB_capture_connect, 0, 1, 1, 1)
        self.pB_capture_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_capture_refresh.setEnabled(True)
        self.pB_capture_refresh.setAutoFillBackground(False)
        self.pB_capture_refresh.setObjectName("pB_capture_refresh")
        self.gridLayout_3.addWidget(self.pB_capture_refresh, 0, 2, 1, 1)
        self.cB_capture_img_size = QtWidgets.QComboBox(self.layoutWidget)
        self.cB_capture_img_size.setCurrentText("")
        self.cB_capture_img_size.setObjectName("cB_capture_img_size")
        self.gridLayout_3.addWidget(self.cB_capture_img_size, 0, 3, 1, 1)
        self.lab_capture_status = QtWidgets.QLabel(self.layoutWidget)
        self.lab_capture_status.setAutoFillBackground(True)
        self.lab_capture_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_capture_status.setObjectName("lab_capture_status")
        self.gridLayout_3.addWidget(self.lab_capture_status, 1, 0, 1, 1)
        self.pB_capture_start_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_capture_start_stop.setEnabled(True)
        self.pB_capture_start_stop.setAutoFillBackground(False)
        self.pB_capture_start_stop.setObjectName("pB_capture_start_stop")
        self.gridLayout_3.addWidget(self.pB_capture_start_stop, 1, 1, 1, 1)
        self.pB_capture_snapshot = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_capture_snapshot.setEnabled(True)
        self.pB_capture_snapshot.setAutoFillBackground(False)
        self.pB_capture_snapshot.setObjectName("pB_capture_snapshot")
        self.gridLayout_3.addWidget(self.pB_capture_snapshot, 1, 2, 1, 1)
        self.cB_capture_img_file_ext = QtWidgets.QComboBox(self.layoutWidget)
        self.cB_capture_img_file_ext.setCurrentText("")
        self.cB_capture_img_file_ext.setObjectName("cB_capture_img_file_ext")
        self.gridLayout_3.addWidget(self.cB_capture_img_file_ext, 1, 3, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_21.setGeometry(QtCore.QRect(450, 0, 801, 541))
        self.groupBox_21.setObjectName("groupBox_21")
        self.chB_eit_image_plot = QtWidgets.QCheckBox(self.groupBox_21)
        self.chB_eit_image_plot.setGeometry(QtCore.QRect(10, 20, 50, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chB_eit_image_plot.sizePolicy().hasHeightForWidth())
        self.chB_eit_image_plot.setSizePolicy(sizePolicy)
        self.chB_eit_image_plot.setObjectName("chB_eit_image_plot")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_21)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 20, 701, 481))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_rec = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_rec.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_rec.setContentsMargins(0, 0, 0, 0)
        self.layout_rec.setObjectName("layout_rec")
        self.label_vmin = QtWidgets.QLabel(self.groupBox_21)
        self.label_vmin.setGeometry(QtCore.QRect(10, 240, 71, 20))
        self.label_vmin.setObjectName("label_vmin")
        self.scalePlot_vmax = QtWidgets.QDoubleSpinBox(self.groupBox_21)
        self.scalePlot_vmax.setGeometry(QtCore.QRect(10, 300, 71, 20))
        self.scalePlot_vmax.setDecimals(4)
        self.scalePlot_vmax.setMinimum(-1000000000000000.0)
        self.scalePlot_vmax.setMaximum(1000000000000000.0)
        self.scalePlot_vmax.setObjectName("scalePlot_vmax")
        self.label_vmax = QtWidgets.QLabel(self.groupBox_21)
        self.label_vmax.setGeometry(QtCore.QRect(10, 280, 71, 20))
        self.label_vmax.setObjectName("label_vmax")
        self.scalePlot_vmin = QtWidgets.QDoubleSpinBox(self.groupBox_21)
        self.scalePlot_vmin.setGeometry(QtCore.QRect(10, 260, 71, 20))
        self.scalePlot_vmin.setDecimals(4)
        self.scalePlot_vmin.setMinimum(-1000000000000000.0)
        self.scalePlot_vmin.setMaximum(1000000000000000.0)
        self.scalePlot_vmin.setObjectName("scalePlot_vmin")
        self.tabW_rec = QtWidgets.QTabWidget(self.centralwidget)
        self.tabW_rec.setGeometry(QtCore.QRect(450, 540, 1471, 491))
        self.tabW_rec.setTabBarAutoHide(True)
        self.tabW_rec.setObjectName("tabW_rec")
        self.tab_meas_voltages = QtWidgets.QWidget()
        self.tab_meas_voltages.setObjectName("tab_meas_voltages")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_meas_voltages)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 10, 1341, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_graphs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_graphs.setContentsMargins(0, 0, 0, 0)
        self.layout_graphs.setObjectName("layout_graphs")
        self.chB_eit_data_Udiffplot = QtWidgets.QCheckBox(self.tab_meas_voltages)
        self.chB_eit_data_Udiffplot.setGeometry(QtCore.QRect(10, 150, 70, 17))
        self.chB_eit_data_Udiffplot.setChecked(True)
        self.chB_eit_data_Udiffplot.setObjectName("chB_eit_data_Udiffplot")
        self.chB_eit_data_Uplot = QtWidgets.QCheckBox(self.tab_meas_voltages)
        self.chB_eit_data_Uplot.setGeometry(QtCore.QRect(10, 130, 51, 17))
        self.chB_eit_data_Uplot.setChecked(True)
        self.chB_eit_data_Uplot.setObjectName("chB_eit_data_Uplot")
        self.chB_eit_data_y_log = QtWidgets.QCheckBox(self.tab_meas_voltages)
        self.chB_eit_data_y_log.setGeometry(QtCore.QRect(10, 180, 48, 17))
        self.chB_eit_data_y_log.setObjectName("chB_eit_data_y_log")
        self.tabW_rec.addTab(self.tab_meas_voltages, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(120, 10, 1341, 461))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_ch_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_ch_graph.setContentsMargins(0, 0, 0, 0)
        self.layout_ch_graph.setObjectName("layout_ch_graph")
        self.cB_monitoring_trans = QtWidgets.QComboBox(self.tab)
        self.cB_monitoring_trans.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.cB_monitoring_trans.setCurrentText("")
        self.cB_monitoring_trans.setObjectName("cB_monitoring_trans")
        self.chB_monitoring_trans_abs = QtWidgets.QCheckBox(self.tab)
        self.chB_monitoring_trans_abs.setGeometry(QtCore.QRect(10, 91, 131, 17))
        self.chB_monitoring_trans_abs.setObjectName("chB_monitoring_trans_abs")
        self.tabW_rec.addTab(self.tab, "")
        self.tab_values = QtWidgets.QWidget()
        self.tab_values.setObjectName("tab_values")
        self.tabW_values = QtWidgets.QTabWidget(self.tab_values)
        self.tabW_values.setGeometry(QtCore.QRect(10, 10, 661, 461))
        self.tabW_values.setObjectName("tabW_values")
        self.tab_Z = QtWidgets.QWidget()
        self.tab_Z.setObjectName("tab_Z")
        self.tableWidgetvoltages_Z = QtWidgets.QTableWidget(self.tab_Z)
        self.tableWidgetvoltages_Z.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z.setObjectName("tableWidgetvoltages_Z")
        self.tableWidgetvoltages_Z.setColumnCount(2)
        self.tableWidgetvoltages_Z.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_Z, "")
        self.tab_real = QtWidgets.QWidget()
        self.tab_real.setObjectName("tab_real")
        self.tableWidgetvoltages_Z_real = QtWidgets.QTableWidget(self.tab_real)
        self.tableWidgetvoltages_Z_real.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z_real.setObjectName("tableWidgetvoltages_Z_real")
        self.tableWidgetvoltages_Z_real.setColumnCount(2)
        self.tableWidgetvoltages_Z_real.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_real.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_real, "")
        self.tab_imag = QtWidgets.QWidget()
        self.tab_imag.setObjectName("tab_imag")
        self.tableWidgetvoltages_Z_imag = QtWidgets.QTableWidget(self.tab_imag)
        self.tableWidgetvoltages_Z_imag.setGeometry(QtCore.QRect(0, 10, 651, 421))
        self.tableWidgetvoltages_Z_imag.setObjectName("tableWidgetvoltages_Z_imag")
        self.tableWidgetvoltages_Z_imag.setColumnCount(2)
        self.tableWidgetvoltages_Z_imag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetvoltages_Z_imag.setHorizontalHeaderItem(1, item)
        self.tabW_values.addTab(self.tab_imag, "")
        self.tab_phase = QtWidgets.QWidget()
        self.tab_phase.setObjectName("tab_phase")
        self.tabW_values.addTab(self.tab_phase, "")
        self.tab_magnitude = QtWidgets.QWidget()
        self.tab_magnitude.setObjectName("tab_magnitude")
        self.tabW_values.addTab(self.tab_magnitude, "")
        self.tabW_rec.addTab(self.tab_values, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 1341, 451))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.layout_monitoring = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.layout_monitoring.setContentsMargins(0, 0, 0, 0)
        self.layout_monitoring.setObjectName("layout_monitoring")
        self.tabW_rec.addTab(self.tab_2, "")
        self.pB_compute = QtWidgets.QPushButton(self.centralwidget)
        self.pB_compute.setGeometry(QtCore.QRect(320, 0, 121, 23))
        self.pB_compute.setAutoFillBackground(False)
        self.pB_compute.setObjectName("pB_compute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1927, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabW_settings.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        self.tabW_reconstruction.setCurrentIndex(0)
        self.tabW_rec.setCurrentIndex(1)
        self.tabW_values.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "EIT device"))
        self.pB_refresh.setStatusTip(_translate("MainWindow", "Refresh the available serial port list (Ctrl + R)"))
        self.pB_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pB_refresh.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pB_connect.setStatusTip(_translate("MainWindow", "Connect to the selected serial port (Shift +C)"))
        self.pB_connect.setText(_translate("MainWindow", "Connect"))
        self.pB_connect.setShortcut(_translate("MainWindow", "Shift+C"))
        self.pB_disconnect.setStatusTip(_translate("MainWindow", "Disconnect the serial port (Shift + D)"))
        self.pB_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pB_disconnect.setShortcut(_translate("MainWindow", "Shift+D"))
        self.cB_ports.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.lab_device_status.setText(_translate("MainWindow", "Not Connected"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Setup of device"))
        self.lab_exc_amp.setText(_translate("MainWindow", "Current Amplitude [mA]"))
        self.lab_burst.setText(_translate("MainWindow", "Burst number"))
        self.lab_minF.setText(_translate("MainWindow", "Min Frequency [Hz]"))
        self.lab_maxF.setText(_translate("MainWindow", "Max Frequency [Hz]"))
        self.lab_steps.setText(_translate("MainWindow", "Steps number"))
        self.lab_scale.setText(_translate("MainWindow", "Scale"))
        self.lab_frame_rate.setText(_translate("MainWindow", "Frame rate [fps]"))
        self.lab_max_frame_rate.setText(_translate("MainWindow", "Max Frame rate [fps]"))
        self.lab_sn.setText(_translate("MainWindow", "S/N"))
        self.lab_ip.setText(_translate("MainWindow", "IP Adress"))
        self.lab_mac.setText(_translate("MainWindow", "MAC Adress"))
        self.chB_dhcp.setText(_translate("MainWindow", "DHCP_Activated"))
        self.chB_exc_stamp.setText(_translate("MainWindow", "Excitation_Stamp"))
        self.chB_current_stamp.setText(_translate("MainWindow", "Current_Stamp"))
        self.chB_time_stamp.setText(_translate("MainWindow", "Time_Stamp"))
        self.lab_output_config.setText(_translate("MainWindow", "Output config"))
        self.groupBox.setTitle(_translate("MainWindow", "Excitation Pattern"))
        item = self.tw_exc_mat_chip.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Inj+ "))
        item = self.tw_exc_mat_chip.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inj-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exc_chip), _translate("MainWindow", "Chip"))
        item = self.tw_exc_mat_model.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Inj+ "))
        item = self.tw_exc_mat_model.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inj-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exc_model), _translate("MainWindow", "Model"))
        self.pB_load_setup.setStatusTip(_translate("MainWindow", "Load parameters from file (*.xlsx)"))
        self.pB_load_setup.setText(_translate("MainWindow", "Load_Setup"))
        self.pB_save_setup.setStatusTip(_translate("MainWindow", "Save parameters to files (*.xlsx)"))
        self.pB_save_setup.setText(_translate("MainWindow", "Save_Setup"))
        self.pB_set_setup.setStatusTip(_translate("MainWindow", "Send measurements parameters to connected device (Shift +S)"))
        self.pB_set_setup.setText(_translate("MainWindow", "Set setup"))
        self.pB_set_setup.setShortcut(_translate("MainWindow", "Shift+S"))
        self.pB_get_setup.setStatusTip(_translate("MainWindow", "Ask measurements parameters from connected device (Shift +G)"))
        self.pB_get_setup.setText(_translate("MainWindow", "Get setup"))
        self.pB_get_setup.setShortcut(_translate("MainWindow", "Shift+G"))
        self.pB_reset.setStatusTip(_translate("MainWindow", "Software reset of the device (reconnection needed after 10-15 sec) (Ctrl + Shift +C)"))
        self.pB_reset.setText(_translate("MainWindow", "Reset"))
        self.pB_reset.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.lab_chip.setText(_translate("MainWindow", "Chip type"))
        self.pB_chip_refresh_ctlg.setStatusTip(_translate("MainWindow", "reload the catalog "))
        self.pB_chip_refresh_ctlg.setText(_translate("MainWindow", "upddate"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_device), _translate("MainWindow", "Device"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Frame infos"))
        self.pB_load_eidors_fwd_solution.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_load_eidors_fwd_solution.setText(_translate("MainWindow", "Load EIDORS fwd solution"))
        self.pB_export_data_meas_vs_eidors.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_export_data_meas_vs_eidors.setText(_translate("MainWindow", "Export measurements vs EIDORS to CSV"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Imaging type"))
        self.lab_ref_frame_idx.setText(_translate("MainWindow", "Reference frame#"))
        self.lab_freq_meas_0.setText(_translate("MainWindow", "Frequence"))
        self.lab_freq_meas_1.setText(_translate("MainWindow", "Frequence "))
        self.chB_eit_imaging_trans_abs.setText(_translate("MainWindow", "Show absolute values"))
        self.lab_actual_frame_cnt.setText(_translate("MainWindow", "Acquisition progress of frame"))
        self.chB_dataset_autosave.setText(_translate("MainWindow", "autosave"))
        self.chB_dataset_save_img.setText(_translate("MainWindow", "save img"))
        self.sB_actual_frame_cnt.setPrefix(_translate("MainWindow", "#"))
        self.pB_start_meas.setStatusTip(_translate("MainWindow", "Start measurement (Ctrl + Shift +Space)"))
        self.pB_start_meas.setText(_translate("MainWindow", "Start"))
        self.pB_start_meas.setShortcut(_translate("MainWindow", "Ctrl+Shift+Space"))
        self.lab_live_meas_status.setText(_translate("MainWindow", "Meas status"))
        self.lE_meas_dataset_dir.setText(_translate("MainWindow", "default_autosave_dir"))
        self.pB_stop_meas.setStatusTip(_translate("MainWindow", "Stop measurement (Esc)"))
        self.pB_stop_meas.setText(_translate("MainWindow", "Stop"))
        self.pB_stop_meas.setShortcut(_translate("MainWindow", "Esc"))
        self.chB_load_after_meas.setText(_translate("MainWindow", "load after meas"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Acquisition), _translate("MainWindow", "Acquisition"))
        self.pB_export_meas_csv.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_export_meas_csv.setText(_translate("MainWindow", "Export measurements to CSV"))
        self.sB_replay_time.setSuffix(_translate("MainWindow", " s"))
        self.pB_load_ref_dataset.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_load_ref_dataset.setText(_translate("MainWindow", "Load reference dataset"))
        self.pB_replay_begin.setStatusTip(_translate("MainWindow", "First frame (Pos1)"))
        self.pB_replay_begin.setShortcut(_translate("MainWindow", "Home"))
        self.pB_replay_back.setStatusTip(_translate("MainWindow", "Previous frame"))
        self.pB_replay_back.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.pB_replay_play.setStatusTip(_translate("MainWindow", "Start Replay of measurements (Ctrl +Space)"))
        self.pB_replay_play.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.pB_replay_next.setStatusTip(_translate("MainWindow", "Next frame"))
        self.pB_replay_next.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.pB_replay_end.setStatusTip(_translate("MainWindow", "Last frame (End)"))
        self.pB_replay_end.setShortcut(_translate("MainWindow", "End"))
        self.pB_replay_stop.setStatusTip(_translate("MainWindow", "Display last meas. frame (End)"))
        self.pB_replay_stop.setShortcut(_translate("MainWindow", "End"))
        self.lab_replay_time.setText(_translate("MainWindow", "Refresh time"))
        self.tE_load_dataset_dir.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">default_</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">loading_</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dirpath</p></body></html>"))
        self.lab_replay_status.setText(_translate("MainWindow", "Replay status"))
        self.lab_current_frame_indx.setText(_translate("MainWindow", "Current frame #"))
        self.pB_meas_dataset_load.setStatusTip(_translate("MainWindow", "Load measurements from a selected directory"))
        self.pB_meas_dataset_load.setText(_translate("MainWindow", "Load measurements"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Replay), _translate("MainWindow", "Replay"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_measurements), _translate("MainWindow", "Measurements"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Reconstruction parameters"))
        self.lab_solver.setText(_translate("MainWindow", "Solver"))
        self.label_vmax_7.setText(_translate("MainWindow", "p"))
        self.label_vmax_8.setText(_translate("MainWindow", "lamda"))
        self.label_vmax_9.setText(_translate("MainWindow", "n"))
        self.label_FEMRefinement_2.setText(_translate("MainWindow", "BackGround"))
        self.tabW_reconstruction.setTabText(self.tabW_reconstruction.indexOf(self.tab_pyeit), _translate("MainWindow", "PyEIT"))
        self.lE_ai_model_dir.setText(_translate("MainWindow", "default_loading_dirpath"))
        self.tabW_reconstruction.setTabText(self.tabW_reconstruction.indexOf(self.tab_nn), _translate("MainWindow", "NN"))
        self.pB_set_reconstruction.setStatusTip(_translate("MainWindow", "Set the reconstruction"))
        self.pB_set_reconstruction.setText(_translate("MainWindow", "Set reconstruction"))
        self.label_FEMRefinement.setText(_translate("MainWindow", "FEM Refinement"))
        self.chB_eit_mdl_normalize.setText(_translate("MainWindow", "Normalize"))
        self.lab_eit_mdl_ctlg.setText(_translate("MainWindow", "EIT model"))
        self.pB_eit_mdl_refresh_ctlg.setStatusTip(_translate("MainWindow", "reload the catalog "))
        self.pB_eit_mdl_refresh_ctlg.setText(_translate("MainWindow", "update"))
        self.lab_log_level.setText(_translate("MainWindow", "log level"))
        self.cB_log_level.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.tabW_settings.setTabText(self.tabW_settings.indexOf(self.tab_eit_model), _translate("MainWindow", "EIT:_model"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Video"))
        self.video_frame.setText(_translate("MainWindow", "Live Video"))
        self.cB_capture_devices.setStatusTip(_translate("MainWindow", "Available serial port list"))
        self.pB_capture_connect.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_connect.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_connect.setText(_translate("MainWindow", "Connect"))
        self.pB_capture_refresh.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_refresh.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_refresh.setText(_translate("MainWindow", "Refresh"))
        self.lab_capture_status.setText(_translate("MainWindow", "Meas status"))
        self.pB_capture_start_stop.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_start_stop.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_start_stop.setText(_translate("MainWindow", "Start capture"))
        self.pB_capture_snapshot.setToolTip(_translate("MainWindow", "test"))
        self.pB_capture_snapshot.setStatusTip(_translate("MainWindow", "Refresh the available serial port list"))
        self.pB_capture_snapshot.setText(_translate("MainWindow", "Snapshot"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Reconstruction"))
        self.chB_eit_image_plot.setText(_translate("MainWindow", "Image"))
        self.label_vmin.setText(_translate("MainWindow", "vmin"))
        self.label_vmax.setText(_translate("MainWindow", "vmax"))
        self.chB_eit_data_Udiffplot.setText(_translate("MainWindow", "Difference"))
        self.chB_eit_data_Uplot.setText(_translate("MainWindow", "Uplot"))
        self.chB_eit_data_y_log.setText(_translate("MainWindow", "y log"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab_meas_voltages), _translate("MainWindow", "Reconstruction data"))
        self.chB_monitoring_trans_abs.setText(_translate("MainWindow", "Show absolute values"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab), _translate("MainWindow", "Channel Monitoring"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_Z), _translate("MainWindow", "Z"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_real.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_real), _translate("MainWindow", "Real"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch1"))
        item = self.tableWidgetvoltages_Z_imag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch2"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_imag), _translate("MainWindow", "Imag"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_phase), _translate("MainWindow", "Phase"))
        self.tabW_values.setTabText(self.tabW_values.indexOf(self.tab_magnitude), _translate("MainWindow", "Magnitude"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab_values), _translate("MainWindow", "Measured values tabs"))
        self.tabW_rec.setTabText(self.tabW_rec.indexOf(self.tab_2), _translate("MainWindow", "Monitoring"))
        self.pB_compute.setStatusTip(_translate("MainWindow", "Stop measurement (Esc)"))
        self.pB_compute.setText(_translate("MainWindow", "Compute"))
        self.pB_compute.setShortcut(_translate("MainWindow", "Esc"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
